// GENERATED by tests/generate-addon-app-modules.mjs, do not edit by hand.
 
// @ts-nocheck
import m0 from 'ember-keyboard/helpers/if-key';
import m1 from 'ember-keyboard/helpers/on-key';
import m2 from 'ember-keyboard/modifiers/on-key';
import m3 from 'ember-keyboard/services/keyboard';

export default {
  './helpers/if-key': m0,
  './helpers/on-key': m1,
  './modifiers/on-key': m2,
  './services/keyboard': m3
};
