// GENERATED by tests/generate-addon-app-modules.mjs, do not edit by hand.
/* eslint-disable */
// @ts-nocheck
import m0 from 'ember-power-select/components/power-select-multiple';
import m1 from 'ember-power-select/components/power-select-multiple/input';
import m2 from 'ember-power-select/components/power-select-multiple/trigger';
import m3 from 'ember-power-select/components/power-select';
import m4 from 'ember-power-select/components/power-select/before-options';
import m5 from 'ember-power-select/components/power-select/input';
import m6 from 'ember-power-select/components/power-select/label';
import m7 from 'ember-power-select/components/power-select/no-matches-message';
import m8 from 'ember-power-select/components/power-select/options';
import m9 from 'ember-power-select/components/power-select/placeholder';
import m10 from 'ember-power-select/components/power-select/power-select-group';
import m11 from 'ember-power-select/components/power-select/search-message';
import m12 from 'ember-power-select/components/power-select/trigger';
import m13 from 'ember-power-select/helpers/ember-power-select-is-equal';
import m14 from 'ember-power-select/helpers/ember-power-select-is-group';
import m15 from 'ember-power-select/helpers/ember-power-select-is-selected-present';
import m16 from 'ember-basic-dropdown/components/basic-dropdown-content';
import m17 from 'ember-basic-dropdown/components/basic-dropdown-trigger';
import m18 from 'ember-basic-dropdown/components/basic-dropdown-wormhole';
import m19 from 'ember-basic-dropdown/components/basic-dropdown';
import m20 from 'ember-basic-dropdown/modifiers/basic-dropdown-trigger';
import m21 from 'ember-truth-helpers/helpers/and';
import m22 from 'ember-truth-helpers/helpers/eq';
import m23 from 'ember-truth-helpers/helpers/gt';
import m24 from 'ember-truth-helpers/helpers/gte';
import m25 from 'ember-truth-helpers/helpers/is-array';
import m26 from 'ember-truth-helpers/helpers/is-empty';
import m27 from 'ember-truth-helpers/helpers/is-equal';
import m28 from 'ember-truth-helpers/helpers/lt';
import m29 from 'ember-truth-helpers/helpers/lte';
import m30 from 'ember-truth-helpers/helpers/not-eq';
import m31 from 'ember-truth-helpers/helpers/not';
import m32 from 'ember-truth-helpers/helpers/or';
import m33 from 'ember-truth-helpers/helpers/xor';
import m34 from '@ember/render-modifiers/modifiers/did-insert';
import m35 from '@ember/render-modifiers/modifiers/did-update';
import m36 from '@ember/render-modifiers/modifiers/will-destroy';
import m37 from 'ember-keyboard/helpers/if-key';
import m38 from 'ember-keyboard/helpers/on-key';
import m39 from 'ember-keyboard/modifiers/on-key';
import m40 from 'ember-keyboard/services/keyboard';
import m41 from 'ember-assign-helper/helpers/assign';

export default {
  './components/power-select-multiple': m0,
  './components/power-select-multiple/input': m1,
  './components/power-select-multiple/trigger': m2,
  './components/power-select': m3,
  './components/power-select/before-options': m4,
  './components/power-select/input': m5,
  './components/power-select/label': m6,
  './components/power-select/no-matches-message': m7,
  './components/power-select/options': m8,
  './components/power-select/placeholder': m9,
  './components/power-select/power-select-group': m10,
  './components/power-select/search-message': m11,
  './components/power-select/trigger': m12,
  './helpers/ember-power-select-is-equal': m13,
  './helpers/ember-power-select-is-group': m14,
  './helpers/ember-power-select-is-selected-present': m15,
  './components/basic-dropdown-content': m16,
  './components/basic-dropdown-trigger': m17,
  './components/basic-dropdown-wormhole': m18,
  './components/basic-dropdown': m19,
  './modifiers/basic-dropdown-trigger': m20,
  './helpers/and': m21,
  './helpers/eq': m22,
  './helpers/gt': m23,
  './helpers/gte': m24,
  './helpers/is-array': m25,
  './helpers/is-empty': m26,
  './helpers/is-equal': m27,
  './helpers/lt': m28,
  './helpers/lte': m29,
  './helpers/not-eq': m30,
  './helpers/not': m31,
  './helpers/or': m32,
  './helpers/xor': m33,
  './modifiers/did-insert': m34,
  './modifiers/did-update': m35,
  './modifiers/will-destroy': m36,
  './helpers/if-key': m37,
  './helpers/on-key': m38,
  './modifiers/on-key': m39,
  './services/keyboard': m40,
  './helpers/assign': m41
};
