/**
 * Generates src/-private/icons.ts: a map from every EUI icon type to a
 * loader for its Ember component, built from vendor/icon/svgs by
 * @svg-jar/plugin (`?unsafe-inline` imports become components rendering the
 * inline svg). Each icon is a dynamic import, so it ends up in its own chunk
 * and apps only download the icons they render; only `empty`, rendered while
 * an icon loads, is imported statically.
 *
 * The icon names come from `typeToPathMap` in
 * src/utils/css-mappings/eui-icon.ts, which stays the source of truth.
 * Files are matched by name anywhere under vendor/icon/svgs (e.g. the
 * `tokens/` folder), like ember-svg-jar's `stripPath` did.
 *
 * Re-run after adding or renaming icons:
 *   node scripts/generate-icons.mjs
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const svgDir = join(root, 'vendor/icon/svgs');
const mappingFile = join(root, 'src/utils/css-mappings/eui-icon.ts');
const outFile = join(root, 'src/-private/icons.ts');

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);

    return statSync(path).isDirectory() ? walk(path) : [path];
  });
}

const filesByName = new Map();

for (const file of walk(svgDir).filter((f) => f.endsWith('.svg'))) {
  const name = file.slice(file.lastIndexOf(sep) + 1, -'.svg'.length);

  if (filesByName.has(name)) {
    throw new Error(`Duplicate icon file name "${name}":\n${filesByName.get(name)}\n${file}`);
  }

  filesByName.set(name, file);
}

const source = readFileSync(mappingFile, 'utf8');
const start = source.indexOf('export const typeToPathMap = {');
const block = source.slice(start, source.indexOf('};', start));
const entries = [...block.matchAll(/^\s+(\w+|'[^']+'):\s*'([^']+)'/gm)].map(
  ([, key, file]) => [key.replace(/'/g, ''), file]
);

if (entries.length === 0) {
  throw new Error(`Could not read typeToPathMap from ${mappingFile}`);
}

const lines = [];
let emptySpecifier;
// @svg-jar/plugin's runtime only keeps viewBox/width/height on the root
// <svg>. EUI's CSS targets `[data-type=logoElastic]`, so root data-type
// attributes are collected here and re-applied by EuiIcon.
const dataTypes = [];

for (const [type, fileName] of entries) {
  const file = filesByName.get(fileName);

  if (!file) {
    throw new Error(`No svg found for icon "${type}" (${fileName}.svg)`);
  }

  const specifier = `${relative(dirname(outFile), file).split(sep).join('/')}?unsafe-inline`;

  if (type === 'empty') emptySpecifier = specifier;

  lines.push(`  ${JSON.stringify(type)}: () => import('${specifier}')`);

  const rootTag = readFileSync(file, 'utf8').match(/<svg\b[^>]*>/)?.[0] ?? '';
  const dataType = rootTag.match(/\sdata-type="([^"]*)"/)?.[1];

  if (dataType) {
    dataTypes.push(`  ${JSON.stringify(type)}: ${JSON.stringify(dataType)}`);
  }
}

if (!emptySpecifier) {
  throw new Error('typeToPathMap has no "empty" icon, needed as the placeholder');
}

writeFileSync(
  outFile,
  `// GENERATED by scripts/generate-icons.mjs, do not edit by hand.
import empty from '${emptySpecifier}';

import type { typeToPathMap } from '../utils/css-mappings/eui-icon.ts';
import type { ComponentLike } from '@glint/template';

export type EuiIconComponent = ComponentLike<{
  Element: SVGSVGElement;
  Blocks: { default: [] };
}>;

export type EuiIconLoader = () => Promise<{ default: EuiIconComponent }>;

/** Rendered while an icon loads. */
export const emptyIcon: EuiIconComponent = empty;

const iconLoaders: Record<keyof typeof typeToPathMap, EuiIconLoader> = {
${lines.join(',\n')}
};

export default iconLoaders;

/** \`data-type\` attributes from the source svgs, used by EUI's CSS. */
export const iconDataTypes: Partial<
  Record<keyof typeof typeToPathMap, string>
> = {
${dataTypes.join(',\n')}
};
`
);

console.log(`wrote ${entries.length} icons`);
