import type EuiAccordion from './components/eui-accordion.gts';
import type EuiAutoSizer from './components/eui-auto-sizer.gts';
import type EuiAvatar from './components/eui-avatar.gts';
import type EuiBadge from './components/eui-badge.gts';
import type EuiBadgeGroup from './components/eui-badge-group.gts';
import type EuiBetaBadge from './components/eui-beta-badge.gts';
import type EuiBottomBar from './components/eui-bottom-bar.gts';
import type EuiBreadcrumbs from './components/eui-breadcrumbs.gts';
import type EuiButton from './components/eui-button.gts';
import type EuiButtonEmpty from './components/eui-button-empty.gts';
import type EuiButtonGroup from './components/eui-button-group.gts';
import type EuiButtonIcon from './components/eui-button-icon.gts';
import type EuiCallOut from './components/eui-call-out.gts';
import type EuiCard from './components/eui-card.gts';
import type EuiCardSelect from './components/eui-card-select.gts';
import type EuiCheckableCard from './components/eui-checkable-card.gts';
import type EuiCheckbox from './components/eui-checkbox.gts';
import type EuiCheckboxGroup from './components/eui-checkbox-group.gts';
import type EuiCode from './components/eui-code.gts';
import type EuiCodeBlock from './components/eui-code-block.gts';
import type EuiCollapsibleNav from './components/eui-collapsible-nav.gts';
import type EuiComboBox from './components/eui-combo-box.gts';
import type EuiComboBoxPill from './components/eui-combo-box-pill.gts';
import type EuiComment from './components/eui-comment.gts';
import type EuiCommentList from './components/eui-comment-list.gts';
import type EuiConfirmModal from './components/eui-confirm-modal.gts';
import type EuiContextMenuItem from './components/eui-context-menu-item.gts';
import type EuiContextMenuPanel from './components/eui-context-menu-panel.gts';
import type EuiCopy from './components/eui-copy.gts';
import type EuiDescribedFormGroup from './components/eui-described-form-group.gts';
import type EuiDescriptionList from './components/eui-description-list.gts';
import type EuiDescriptionListDescription from './components/eui-description-list-description.gts';
import type EuiDescriptionListTitle from './components/eui-description-list-title.gts';
import type EuiDualRange from './components/eui-dual-range.gts';
import type EuiEmptyPrompt from './components/eui-empty-prompt.gts';
import type EuiFieldNumber from './components/eui-field-number.gts';
import type EuiFieldPassword from './components/eui-field-password.gts';
import type EuiFieldSearch from './components/eui-field-search.gts';
import type EuiFieldText from './components/eui-field-text.gts';
import type EuiFilePicker from './components/eui-file-picker.gts';
import type EuiFlexGrid from './components/eui-flex-grid.gts';
import type EuiFlexGroup from './components/eui-flex-group.gts';
import type EuiFlexItem from './components/eui-flex-item.gts';
import type EuiFlyout from './components/eui-flyout.gts';
import type EuiFlyoutBody from './components/eui-flyout-body.gts';
import type EuiFlyoutFooter from './components/eui-flyout-footer.gts';
import type EuiFlyoutHeader from './components/eui-flyout-header.gts';
import type EuiForm from './components/eui-form.gts';
import type EuiFormControlLayout from './components/eui-form-control-layout.gts';
import type EuiFormControlLayoutDelimited from './components/eui-form-control-layout-delimited.gts';
import type EuiFormControlLayoutIcons from './components/eui-form-control-layout-icons.gts';
import type EuiFormErrorText from './components/eui-form-error-text.gts';
import type EuiFormHelpText from './components/eui-form-help-text.gts';
import type EuiFormLabel from './components/eui-form-label.gts';
import type EuiFormRow from './components/eui-form-row.gts';
import type EuiGlobalToastList from './components/eui-global-toast-list.gts';
import type EuiHeader from './components/eui-header.gts';
import type EuiHeaderAlert from './components/eui-header-alert.gts';
import type EuiHeaderBreadcrumbs from './components/eui-header-breadcrumbs.gts';
import type EuiHeaderLink from './components/eui-header-link.gts';
import type EuiHeaderLinks from './components/eui-header-links.gts';
import type EuiHeaderLogo from './components/eui-header-logo.gts';
import type EuiHeaderSection from './components/eui-header-section.gts';
import type EuiHeaderSectionItem from './components/eui-header-section-item.gts';
import type EuiHeaderSectionItemButton from './components/eui-header-section-item-button.gts';
import type EuiHealth from './components/eui-health.gts';
import type EuiHideFor from './components/eui-hide-for.gts';
import type EuiHorizontalRule from './components/eui-horizontal-rule.gts';
import type EuiIcon from './components/eui-icon.gts';
import type EuiIconTip from './components/eui-icon-tip.gts';
import type EuiImage from './components/eui-image.gts';
import type EuiKeyPadMenu from './components/eui-key-pad-menu.gts';
import type EuiKeyPadMenuItem from './components/eui-key-pad-menu-item.gts';
import type EuiLink from './components/eui-link.gts';
import type EuiListGroup from './components/eui-list-group.gts';
import type EuiListGroupItem from './components/eui-list-group-item.gts';
import type EuiLoadingContent from './components/eui-loading-content.gts';
import type EuiLoadingLogo from './components/eui-loading-logo.gts';
import type EuiLoadingSpinner from './components/eui-loading-spinner.gts';
import type EuiMarkdownEditor from './components/eui-markdown-editor.gts';
import type EuiMarkdownFormat from './components/eui-markdown-format.gts';
import type EuiModal from './components/eui-modal.gts';
import type EuiModalBody from './components/eui-modal-body.gts';
import type EuiModalFooter from './components/eui-modal-footer.gts';
import type EuiModalHeader from './components/eui-modal-header.gts';
import type EuiModalHeaderTitle from './components/eui-modal-header-title.gts';
import type EuiNotificationBadge from './components/eui-notification-badge.gts';
import type EuiNotificationEvent from './components/eui-notification-event.gts';
import type EuiNotificationEventMessages from './components/eui-notification-event-messages.gts';
import type EuiNotificationEventMeta from './components/eui-notification-event-meta.gts';
import type EuiNotificationEventReadButton from './components/eui-notification-event-read-button.gts';
import type EuiNotificationEventReadIcon from './components/eui-notification-event-read-icon.gts';
import type EuiOverlayMask from './components/eui-overlay-mask.gts';
import type EuiPage from './components/eui-page.gts';
import type EuiPageBody from './components/eui-page-body.gts';
import type EuiPageContent from './components/eui-page-content.gts';
import type EuiPageContentBody from './components/eui-page-content-body.gts';
import type EuiPageContentHeader from './components/eui-page-content-header.gts';
import type EuiPageContentHeaderSection from './components/eui-page-content-header-section.gts';
import type EuiPageHeader from './components/eui-page-header.gts';
import type EuiPageHeaderSection from './components/eui-page-header-section.gts';
import type EuiPageSideBar from './components/eui-page-side-bar.gts';
import type EuiPageTemplate from './components/eui-page-template.gts';
import type EuiPagination from './components/eui-pagination.gts';
import type EuiPaginationButton from './components/eui-pagination-button.gts';
import type EuiPanel from './components/eui-panel.gts';
import type EuiPopover from './components/eui-popover.gts';
import type EuiPopoverFooter from './components/eui-popover-footer.gts';
import type EuiPopoverTitle from './components/eui-popover-title.gts';
import type EuiPortal from './components/eui-portal.gts';
import type EuiProgress from './components/eui-progress.gts';
import type EuiRadio from './components/eui-radio.gts';
import type EuiRadioGroup from './components/eui-radio-group.gts';
import type EuiRange from './components/eui-range.gts';
import type EuiRangeHighlight from './components/eui-range-highlight.gts';
import type EuiRangeInput from './components/eui-range-input.gts';
import type EuiRangeLabel from './components/eui-range-label.gts';
import type EuiRangeLevels from './components/eui-range-levels.gts';
import type EuiRangeSlider from './components/eui-range-slider.gts';
import type EuiRangeThumb from './components/eui-range-thumb.gts';
import type EuiRangeTicks from './components/eui-range-ticks.gts';
import type EuiRangeTooltip from './components/eui-range-tooltip.gts';
import type EuiRangeTrack from './components/eui-range-track.gts';
import type EuiRangeWrapper from './components/eui-range-wrapper.gts';
import type EuiSelect from './components/eui-select.gts';
import type EuiSelectableListItem from './components/eui-selectable-list-item.gts';
import type EuiShowFor from './components/eui-show-for.gts';
import type EuiSideNav from './components/eui-side-nav.gts';
import type EuiSpacer from './components/eui-spacer.gts';
import type EuiStat from './components/eui-stat.gts';
import type EuiStep from './components/eui-step.gts';
import type EuiStepHorizontal from './components/eui-step-horizontal.gts';
import type EuiStepNumber from './components/eui-step-number.gts';
import type EuiSteps from './components/eui-steps.gts';
import type EuiSubSteps from './components/eui-sub-steps.gts';
import type EuiSuperDatePicker from './components/eui-super-date-picker.gts';
import type EuiSwitch from './components/eui-switch.gts';
import type EuiTab from './components/eui-tab.gts';
import type EuiTabbedContent from './components/eui-tabbed-content.gts';
import type EuiTabs from './components/eui-tabs.gts';
import type EuiText from './components/eui-text.gts';
import type EuiTextAlign from './components/eui-text-align.gts';
import type EuiTextArea from './components/eui-text-area.gts';
import type EuiTextColor from './components/eui-text-color.gts';
import type EuiTitle from './components/eui-title.gts';
import type EuiToast from './components/eui-toast.gts';
import type EuiToolTip from './components/eui-tool-tip.gts';
import type EuiToolTipPopover from './components/eui-tool-tip-popover.gts';
import type TextBlock from './components/text-block.gts';
import type argOrDefault from './helpers/arg-or-default.ts';
import type castTo from './helpers/cast-to.ts';
import type classNames from './helpers/class-names.ts';
import type getEuiConfig from './helpers/get-eui-config.ts';
import type inlineStyles from './helpers/inline-styles.ts';
import type isColorDark from './helpers/is-color-dark.ts';
import type useState from './helpers/use-state.ts';
import type mutationObserver from './modifiers/mutation-observer.ts';
import type outsideClickDetector from './modifiers/outside-click-detector.ts';
import type resizeObserver from './modifiers/resize-observer.ts';
import type screenReaderOnly from './modifiers/screen-reader-only.ts';
import type simpleStyle from './modifiers/simple-style.ts';
import type validatableControl from './modifiers/validatable-control.ts';

export default interface EmberEuiRegistry {
  EuiButton: typeof EuiButton;
  'eui-button': typeof EuiButton;
  EuiButtonEmpty: typeof EuiButtonEmpty;
  'eui-button-empty': typeof EuiButtonEmpty;
  EuiAccordion: typeof EuiAccordion;
  'eui-accordion': typeof EuiAccordion;
  EuiAutoSizer: typeof EuiAutoSizer;
  'eui-auto-sizer': typeof EuiAutoSizer;
  EuiAvatar: typeof EuiAvatar;
  'eui-avatar': typeof EuiAvatar;
  EuiBadge: typeof EuiBadge;
  'eui-badge': typeof EuiBadge;
  EuiBetaBadge: typeof EuiBetaBadge;
  'eui-beta-badge': typeof EuiBetaBadge;
  EuiBreadcrumbs: typeof EuiBreadcrumbs;
  'eui-breadcrumbs': typeof EuiBreadcrumbs;
  EuiBadgeGroup: typeof EuiBadgeGroup;
  'eui-badge-group': typeof EuiBadgeGroup;
  EuiBottomBar: typeof EuiBottomBar;
  'eui-bottom-bar': typeof EuiBottomBar;
  EuiButtonGroup: typeof EuiButtonGroup;
  'eui-button-group': typeof EuiButtonGroup;
  EuiButtonIcon: typeof EuiButtonIcon;
  'eui-button-icon': typeof EuiButtonIcon;
  EuiCallOut: typeof EuiCallOut;
  'eui-call-out': typeof EuiCallOut;
  EuiCardSelect: typeof EuiCardSelect;
  'eui-card-select': typeof EuiCardSelect;
  EuiCheckbox: typeof EuiCheckbox;
  'eui-checkbox': typeof EuiCheckbox;
  EuiCode: typeof EuiCode;
  'eui-code': typeof EuiCode;
  EuiCodeBlock: typeof EuiCodeBlock;
  'eui-code-block': typeof EuiCodeBlock;
  EuiCard: typeof EuiCard;
  'eui-card': typeof EuiCard;
  EuiCheckableCard: typeof EuiCheckableCard;
  'eui-checkable-card': typeof EuiCheckableCard;
  EuiCheckboxGroup: typeof EuiCheckboxGroup;
  'eui-checkbox-group': typeof EuiCheckboxGroup;
  EuiCollapsibleNav: typeof EuiCollapsibleNav;
  'eui-collapsible-nav': typeof EuiCollapsibleNav;
  EuiComboBoxPill: typeof EuiComboBoxPill;
  'eui-combo-box-pill': typeof EuiComboBoxPill;
  EuiComboBox: typeof EuiComboBox;
  'eui-combo-box': typeof EuiComboBox;
  EuiCommentList: typeof EuiCommentList;
  'eui-comment-list': typeof EuiCommentList;
  EuiComment: typeof EuiComment;
  'eui-comment': typeof EuiComment;
  EuiConfirmModal: typeof EuiConfirmModal;
  'eui-confirm-modal': typeof EuiConfirmModal;
  EuiContextMenuItem: typeof EuiContextMenuItem;
  'eui-context-menu-item': typeof EuiContextMenuItem;
  EuiContextMenuPanel: typeof EuiContextMenuPanel;
  'eui-context-menu-panel': typeof EuiContextMenuPanel;
  EuiCopy: typeof EuiCopy;
  'eui-copy': typeof EuiCopy;
  EuiDescribedFormGroup: typeof EuiDescribedFormGroup;
  'eui-described-form-group': typeof EuiDescribedFormGroup;
  EuiDescriptionList: typeof EuiDescriptionList;
  'eui-description-list': typeof EuiDescriptionList;
  EuiDescriptionListTitle: typeof EuiDescriptionListTitle;
  'eui-description-list-title': typeof EuiDescriptionListTitle;
  EuiDescriptionListDescription: typeof EuiDescriptionListDescription;
  'eui-description-list-description': typeof EuiDescriptionListDescription;
  EuiDualRange: typeof EuiDualRange;
  'eui-dual-range': typeof EuiDualRange;
  EuiEmptyPrompt: typeof EuiEmptyPrompt;
  'eui-empty-prompt': typeof EuiEmptyPrompt;
  EuiFieldNumber: typeof EuiFieldNumber;
  'eui-field-number': typeof EuiFieldNumber;
  EuiFieldPassword: typeof EuiFieldPassword;
  'eui-field-password': typeof EuiFieldPassword;
  EuiFieldSearch: typeof EuiFieldSearch;
  'eui-field-search': typeof EuiFieldSearch;
  EuiFieldText: typeof EuiFieldText;
  'eui-field-text': typeof EuiFieldText;
  EuiTextArea: typeof EuiTextArea;
  'eui-text-area': typeof EuiTextArea;
  EuiFilePicker: typeof EuiFilePicker;
  'eui-file-picker': typeof EuiFilePicker;
  EuiFlexGrid: typeof EuiFlexGrid;
  'eui-flex-grid': typeof EuiFlexGrid;
  EuiFlexGroup: typeof EuiFlexGroup;
  'eui-flex-group': typeof EuiFlexGroup;
  EuiFlexItem: typeof EuiFlexItem;
  'eui-flex-item': typeof EuiFlexItem;
  EuiFlyout: typeof EuiFlyout;
  'eui-flyout': typeof EuiFlyout;
  EuiFlyoutBody: typeof EuiFlyoutBody;
  'eui-flyout-body': typeof EuiFlyoutBody;
  EuiFlyoutFooter: typeof EuiFlyoutFooter;
  'eui-flyout-footer': typeof EuiFlyoutFooter;
  EuiFlyoutHeader: typeof EuiFlyoutHeader;
  'eui-flyout-header': typeof EuiFlyoutHeader;
  EuiForm: typeof EuiForm;
  'eui-form': typeof EuiForm;
  EuiFormControlLayout: typeof EuiFormControlLayout;
  'eui-form-control-layout': typeof EuiFormControlLayout;
  EuiFormControlLayoutDelimited: typeof EuiFormControlLayoutDelimited;
  'eui-form-control-layout-delimited': typeof EuiFormControlLayoutDelimited;
  EuiFormControlLayoutIcons: typeof EuiFormControlLayoutIcons;
  'eui-form-control-layout-icons': typeof EuiFormControlLayoutIcons;
  EuiFormErrorText: typeof EuiFormErrorText;
  'eui-form-error-text': typeof EuiFormErrorText;
  EuiFormHelpText: typeof EuiFormHelpText;
  'eui-form-help-text': typeof EuiFormHelpText;
  EuiFormLabel: typeof EuiFormLabel;
  'eui-form-label': typeof EuiFormLabel;
  EuiFormRow: typeof EuiFormRow;
  'eui-form-row': typeof EuiFormRow;
  EuiHeader: typeof EuiHeader;
  'eui-header': typeof EuiHeader;
  EuiHeaderAlert: typeof EuiHeaderAlert;
  'eui-header-alert': typeof EuiHeaderAlert;
  EuiHeaderBreadcrumbs: typeof EuiHeaderBreadcrumbs;
  'eui-header-breadcrumbs': typeof EuiHeaderBreadcrumbs;
  EuiHeaderLink: typeof EuiHeaderLink;
  'eui-header-link': typeof EuiHeaderLink;
  EuiHeaderLinks: typeof EuiHeaderLinks;
  'eui-header-links': typeof EuiHeaderLinks;
  EuiHeaderLogo: typeof EuiHeaderLogo;
  'eui-header-logo': typeof EuiHeaderLogo;
  EuiHeaderSection: typeof EuiHeaderSection;
  'eui-header-section': typeof EuiHeaderSection;
  EuiHeaderSectionItem: typeof EuiHeaderSectionItem;
  'eui-header-section-item': typeof EuiHeaderSectionItem;
  EuiHeaderSectionItemButton: typeof EuiHeaderSectionItemButton;
  'eui-header-section-item-button': typeof EuiHeaderSectionItemButton;
  EuiHealth: typeof EuiHealth;
  'eui-health': typeof EuiHealth;
  EuiHideFor: typeof EuiHideFor;
  'eui-hide-for': typeof EuiHideFor;
  EuiHorizontalRule: typeof EuiHorizontalRule;
  'eui-horizontal-rule': typeof EuiHorizontalRule;
  EuiIcon: typeof EuiIcon;
  'eui-icon': typeof EuiIcon;
  EuiIconTip: typeof EuiIconTip;
  'eui-icon-tip': typeof EuiIconTip;
  EuiImage: typeof EuiImage;
  'eui-image': typeof EuiImage;
  EuiKeyPadMenu: typeof EuiKeyPadMenu;
  'eui-key-pad-menu': typeof EuiKeyPadMenu;
  EuiKeyPadMenuItem: typeof EuiKeyPadMenuItem;
  'eui-key-pad-menu-item': typeof EuiKeyPadMenuItem;
  EuiLink: typeof EuiLink;
  'eui-link': typeof EuiLink;
  EuiListGroupItem: typeof EuiListGroupItem;
  'eui-list-group-item': typeof EuiListGroupItem;
  EuiListGroup: typeof EuiListGroup;
  'eui-list-group': typeof EuiListGroup;
  EuiLoadingContent: typeof EuiLoadingContent;
  'eui-loading-content': typeof EuiLoadingContent;
  EuiLoadingLogo: typeof EuiLoadingLogo;
  'eui-loading-logo': typeof EuiLoadingLogo;
  EuiLoadingSpinner: typeof EuiLoadingSpinner;
  'eui-loading-spinner': typeof EuiLoadingSpinner;
  EuiModal: typeof EuiModal;
  'eui-modal': typeof EuiModal;
  EuiModalBody: typeof EuiModalBody;
  'eui-modal-body': typeof EuiModalBody;
  EuiModalFooter: typeof EuiModalFooter;
  'eui-modal-footer': typeof EuiModalFooter;
  EuiModalHeader: typeof EuiModalHeader;
  'eui-modal-header': typeof EuiModalHeader;
  EuiModalHeaderTitle: typeof EuiModalHeaderTitle;
  'eui-modal-header-title': typeof EuiModalHeaderTitle;
  EuiMarkdownEditor: typeof EuiMarkdownEditor;
  'eui-markdown-editor': typeof EuiMarkdownEditor;
  EuiMarkdownFormat: typeof EuiMarkdownFormat;
  'eui-markdown-format': typeof EuiMarkdownFormat;
  EuiNotificationBadge: typeof EuiNotificationBadge;
  'eui-notification-badge': typeof EuiNotificationBadge;
  EuiOverlayMask: typeof EuiOverlayMask;
  'eui-overlay-mask': typeof EuiOverlayMask;
  EuiPage: typeof EuiPage;
  'eui-page': typeof EuiPage;
  EuiPageBody: typeof EuiPageBody;
  'eui-page-body': typeof EuiPageBody;
  EuiPageContent: typeof EuiPageContent;
  'eui-page-content': typeof EuiPageContent;
  EuiPageContentBody: typeof EuiPageContentBody;
  'eui-page-content-body': typeof EuiPageContentBody;
  EuiPageContentHeader: typeof EuiPageContentHeader;
  'eui-page-content-header': typeof EuiPageContentHeader;
  EuiPageContentHeaderSection: typeof EuiPageContentHeaderSection;
  'eui-page-content-header-section': typeof EuiPageContentHeaderSection;
  EuiPageHeader: typeof EuiPageHeader;
  'eui-page-header': typeof EuiPageHeader;
  EuiPageHeaderSection: typeof EuiPageHeaderSection;
  'eui-page-header-section': typeof EuiPageHeaderSection;
  EuiPageSideBar: typeof EuiPageSideBar;
  'eui-page-side-bar': typeof EuiPageSideBar;
  EuiPagination: typeof EuiPagination;
  'eui-pagination': typeof EuiPagination;
  EuiPanel: typeof EuiPanel;
  'eui-panel': typeof EuiPanel;
  EuiPopover: typeof EuiPopover;
  'eui-popover': typeof EuiPopover;
  EuiPopoverTitle: typeof EuiPopoverTitle;
  'eui-popover-title': typeof EuiPopoverTitle;
  EuiPopoverFooter: typeof EuiPopoverFooter;
  'eui-popover-footer': typeof EuiPopoverFooter;
  EuiPortal: typeof EuiPortal;
  'eui-portal': typeof EuiPortal;
  EuiProgress: typeof EuiProgress;
  'eui-progress': typeof EuiProgress;
  EuiRange: typeof EuiRange;
  'eui-range': typeof EuiRange;
  EuiNotificationEvent: typeof EuiNotificationEvent;
  'eui-notification-event': typeof EuiNotificationEvent;
  EuiNotificationEventMessages: typeof EuiNotificationEventMessages;
  'eui-notification-event-messages': typeof EuiNotificationEventMessages;
  EuiNotificationEventMeta: typeof EuiNotificationEventMeta;
  'eui-notification-event-meta': typeof EuiNotificationEventMeta;
  EuiNotificationEventReadButton: typeof EuiNotificationEventReadButton;
  'eui-notification-event-read-button': typeof EuiNotificationEventReadButton;
  EuiNotificationEventReadIcon: typeof EuiNotificationEventReadIcon;
  'eui-notification-event-read-icon': typeof EuiNotificationEventReadIcon;
  EuiPageTemplate: typeof EuiPageTemplate;
  'eui-page-template': typeof EuiPageTemplate;
  EuiPaginationButton: typeof EuiPaginationButton;
  'eui-pagination-button': typeof EuiPaginationButton;
  EuiRangeHighlight: typeof EuiRangeHighlight;
  'eui-range-highlight': typeof EuiRangeHighlight;
  EuiRangeInput: typeof EuiRangeInput;
  'eui-range-input': typeof EuiRangeInput;
  EuiRangeLabel: typeof EuiRangeLabel;
  'eui-range-label': typeof EuiRangeLabel;
  EuiRangeLevels: typeof EuiRangeLevels;
  'eui-range-levels': typeof EuiRangeLevels;
  EuiRangeSlider: typeof EuiRangeSlider;
  'eui-range-slider': typeof EuiRangeSlider;
  EuiRangeThumb: typeof EuiRangeThumb;
  'eui-range-thumb': typeof EuiRangeThumb;
  EuiRangeTicks: typeof EuiRangeTicks;
  'eui-range-ticks': typeof EuiRangeTicks;
  EuiRadio: typeof EuiRadio;
  'eui-radio': typeof EuiRadio;
  EuiRadioGroup: typeof EuiRadioGroup;
  'eui-radio-group': typeof EuiRadioGroup;
  EuiRangeTooltip: typeof EuiRangeTooltip;
  'eui-range-tooltip': typeof EuiRangeTooltip;
  EuiRangeTrack: typeof EuiRangeTrack;
  'eui-range-track': typeof EuiRangeTrack;
  EuiRangeWrapper: typeof EuiRangeWrapper;
  'eui-range-wrapper': typeof EuiRangeWrapper;
  EuiSelect: typeof EuiSelect;
  'eui-select': typeof EuiSelect;
  EuiSelectableListItem: typeof EuiSelectableListItem;
  'eui-selectable-list-item': typeof EuiSelectableListItem;
  EuiShowFor: typeof EuiShowFor;
  'eui-show-for': typeof EuiShowFor;
  EuiSideNav: typeof EuiSideNav;
  'eui-side-nav': typeof EuiSideNav;
  EuiSpacer: typeof EuiSpacer;
  'eui-spacer': typeof EuiSpacer;
  EuiStat: typeof EuiStat;
  'eui-stat': typeof EuiStat;
  EuiStep: typeof EuiStep;
  'eui-step': typeof EuiStep;
  EuiSteps: typeof EuiSteps;
  'eui-steps': typeof EuiSteps;
  EuiStepHorizontal: typeof EuiStepHorizontal;
  'eui-step-horizontal': typeof EuiStepHorizontal;
  EuiStepNumber: typeof EuiStepNumber;
  'eui-step-number': typeof EuiStepNumber;
  EuiSubSteps: typeof EuiSubSteps;
  'eui-sub-steps': typeof EuiSubSteps;
  EuiSuperDatePicker: typeof EuiSuperDatePicker;
  'eui-super-date-picker': typeof EuiSuperDatePicker;
  EuiSwitch: typeof EuiSwitch;
  'eui-switch': typeof EuiSwitch;
  EuiTab: typeof EuiTab;
  'eui-tab': typeof EuiTab;
  EuiTabbedContent: typeof EuiTabbedContent;
  'eui-tabbed-content': typeof EuiTabbedContent;
  EuiTabs: typeof EuiTabs;
  'eui-tabs': typeof EuiTabs;
  EuiTextAlign: typeof EuiTextAlign;
  'eui-text-align': typeof EuiTextAlign;
  EuiTextColor: typeof EuiTextColor;
  'eui-text-color': typeof EuiTextColor;
  EuiText: typeof EuiText;
  'eui-text': typeof EuiText;
  EuiToast: typeof EuiToast;
  'eui-toast': typeof EuiToast;
  EuiTitle: typeof EuiTitle;
  'eui-title': typeof EuiTitle;
  EuiToolTipPopover: typeof EuiToolTipPopover;
  'eui-tool-tip-popover': typeof EuiToolTipPopover;
  EuiToolTip: typeof EuiToolTip;
  'eui-tool-tip': typeof EuiToolTip;
  EuiGlobalToastList: typeof EuiGlobalToastList;
  'eui-global-toast-list': typeof EuiGlobalToastList;
  TextBlock: typeof TextBlock;
  'text-block': typeof TextBlock;
  'arg-or-default': typeof argOrDefault;
  'cast-to': typeof castTo;
  'class-names': typeof classNames;
  'inline-styles': typeof inlineStyles;
  'is-color-dark': typeof isColorDark;
  'use-state': typeof useState;
  'get-eui-config': typeof getEuiConfig;
  'mutation-observer': typeof mutationObserver;
  'outside-click-detector': typeof outsideClickDetector;
  'resize-observer': typeof resizeObserver;
  'screen-reader-only': typeof screenReaderOnly;
  'simple-style': typeof simpleStyle;
  'validatable-control': typeof validatableControl;
}
