import type EuiAccordion from './components/eui-accordion';
import type EuiAutoSizer from './components/eui-auto-sizer';
import type EuiAvatar from './components/eui-avatar';
import type EuiBadge from './components/eui-badge';
import type EuiBadgeGroup from './components/eui-badge-group';
import type EuiBetaBadge from './components/eui-beta-badge';
import type EuiBottomBar from './components/eui-bottom-bar';
import type EuiBreadcrumbs from './components/eui-breadcrumbs';
import type EuiButton from './components/eui-button';
import type EuiButtonEmpty from './components/eui-button-empty';
import type EuiButtonGroup from './components/eui-button-group';
import type EuiButtonIcon from './components/eui-button-icon';
import type EuiCallOut from './components/eui-call-out';
import type EuiCard from './components/eui-card';
import type EuiCardSelect from './components/eui-card-select';
import type EuiCheckableCard from './components/eui-checkable-card';
import type EuiCheckbox from './components/eui-checkbox';
import type EuiCheckboxGroup from './components/eui-checkbox-group';
import type EuiCode from './components/eui-code';
import type EuiCodeBlock from './components/eui-code-block';
import type EuiCollapsibleNav from './components/eui-collapsible-nav';
import type EuiComboBox from './components/eui-combo-box';
import type EuiComboBoxPill from './components/eui-combo-box-pill';
import type EuiComment from './components/eui-comment';
import type EuiCommentList from './components/eui-comment-list';
import type EuiConfirmModal from './components/eui-confirm-modal';
import type EuiContextMenuItem from './components/eui-context-menu-item';
import type EuiContextMenuPanel from './components/eui-context-menu-panel';
import type EuiCopy from './components/eui-copy';
import type EuiDescribedFormGroup from './components/eui-described-form-group';
import type EuiDescriptionList from './components/eui-description-list';
import type EuiDescriptionListDescription from './components/eui-description-list-description';
import type EuiDescriptionListTitle from './components/eui-description-list-title';
import type EuiDualRange from './components/eui-dual-range';
import type EuiEmptyPrompt from './components/eui-empty-prompt';
import type EuiFieldNumber from './components/eui-field-number';
import type EuiFieldPassword from './components/eui-field-password';
import type EuiFieldSearch from './components/eui-field-search';
import type EuiFieldText from './components/eui-field-text';
import type EuiFilePicker from './components/eui-file-picker';
import type EuiFlexGrid from './components/eui-flex-grid';
import type EuiFlexGroup from './components/eui-flex-group';
import type EuiFlexItem from './components/eui-flex-item';
import type EuiFlyout from './components/eui-flyout';
import type EuiFlyoutBody from './components/eui-flyout-body';
import type EuiFlyoutFooter from './components/eui-flyout-footer';
import type EuiFlyoutHeader from './components/eui-flyout-header';
import type EuiForm from './components/eui-form';
import type EuiFormControlLayout from './components/eui-form-control-layout';
import type EuiFormControlLayoutDelimited from './components/eui-form-control-layout-delimited';
import type EuiFormControlLayoutIcons from './components/eui-form-control-layout-icons';
import type EuiFormErrorText from './components/eui-form-error-text';
import type EuiFormHelpText from './components/eui-form-help-text';
import type EuiFormLabel from './components/eui-form-label';
import type EuiFormRow from './components/eui-form-row';
import type EuiGlobalToastList from './components/eui-global-toast-list';
import type EuiHeader from './components/eui-header';
import type EuiHeaderAlert from './components/eui-header-alert';
import type EuiHeaderBreadcrumbs from './components/eui-header-breadcrumbs';
import type EuiHeaderLink from './components/eui-header-link';
import type EuiHeaderLinks from './components/eui-header-links';
import type EuiHeaderLogo from './components/eui-header-logo';
import type EuiHeaderSection from './components/eui-header-section';
import type EuiHeaderSectionItem from './components/eui-header-section-item';
import type EuiHeaderSectionItemButton from './components/eui-header-section-item-button';
import type EuiHealth from './components/eui-health';
import type EuiHideFor from './components/eui-hide-for';
import type EuiHorizontalRule from './components/eui-horizontal-rule';
import type EuiIcon from './components/eui-icon';
import type EuiIconTip from './components/eui-icon-tip';
import type EuiImage from './components/eui-image';
import type EuiKeyPadMenu from './components/eui-key-pad-menu';
import type EuiKeyPadMenuItem from './components/eui-key-pad-menu-item';
import type EuiLink from './components/eui-link';
import type EuiListGroup from './components/eui-list-group';
import type EuiListGroupItem from './components/eui-list-group-item';
import type EuiLoadingContent from './components/eui-loading-content';
import type EuiLoadingLogo from './components/eui-loading-logo';
import type EuiLoadingSpinner from './components/eui-loading-spinner';
import type EuiMarkdownEditor from './components/eui-markdown-editor';
import type EuiMarkdownFormat from './components/eui-markdown-format';
import type EuiModal from './components/eui-modal';
import type EuiModalBody from './components/eui-modal-body';
import type EuiModalFooter from './components/eui-modal-footer';
import type EuiModalHeader from './components/eui-modal-header';
import type EuiModalHeaderTitle from './components/eui-modal-header-title';
import type EuiNotificationBadge from './components/eui-notification-badge';
import type EuiNotificationEvent from './components/eui-notification-event';
import type EuiNotificationEventMessages from './components/eui-notification-event-messages';
import type EuiNotificationEventMeta from './components/eui-notification-event-meta';
import type EuiNotificationEventReadButton from './components/eui-notification-event-read-button';
import type EuiNotificationEventReadIcon from './components/eui-notification-event-read-icon';
import type EuiOverlayMask from './components/eui-overlay-mask';
import type EuiPage from './components/eui-page';
import type EuiPageBody from './components/eui-page-body';
import type EuiPageContent from './components/eui-page-content';
import type EuiPageContentBody from './components/eui-page-content-body';
import type EuiPageContentHeader from './components/eui-page-content-header';
import type EuiPageContentHeaderSection from './components/eui-page-content-header-section';
import type EuiPageHeader from './components/eui-page-header';
import type EuiPageHeaderSection from './components/eui-page-header-section';
import type EuiPageSideBar from './components/eui-page-side-bar';
import type EuiPageTemplate from './components/eui-page-template';
import type EuiPagination from './components/eui-pagination';
import type EuiPaginationButton from './components/eui-pagination-button';
import type EuiPanel from './components/eui-panel';
import type EuiPopover from './components/eui-popover';
import type EuiPopoverFooter from './components/eui-popover-footer';
import type EuiPopoverTitle from './components/eui-popover-title';
import type EuiPortal from './components/eui-portal';
import type EuiProgress from './components/eui-progress';
import type EuiRadio from './components/eui-radio';
import type EuiRadioGroup from './components/eui-radio-group';
import type EuiRange from './components/eui-range';
import type EuiRangeHighlight from './components/eui-range-highlight';
import type EuiRangeInput from './components/eui-range-input';
import type EuiRangeLabel from './components/eui-range-label';
import type EuiRangeLevels from './components/eui-range-levels';
import type EuiRangeSlider from './components/eui-range-slider';
import type EuiRangeThumb from './components/eui-range-thumb';
import type EuiRangeTicks from './components/eui-range-ticks';
import type EuiRangeTooltip from './components/eui-range-tooltip';
import type EuiRangeTrack from './components/eui-range-track';
import type EuiRangeWrapper from './components/eui-range-wrapper';
import type EuiSelect from './components/eui-select';
import type EuiSelectableListItem from './components/eui-selectable-list-item';
import type EuiShowFor from './components/eui-show-for';
import type EuiSideNav from './components/eui-side-nav';
import type EuiSpacer from './components/eui-spacer';
import type EuiStat from './components/eui-stat';
import type EuiStep from './components/eui-step';
import type EuiStepHorizontal from './components/eui-step-horizontal';
import type EuiStepNumber from './components/eui-step-number';
import type EuiSteps from './components/eui-steps';
import type EuiSubSteps from './components/eui-sub-steps';
import type EuiSuperDatePicker from './components/eui-super-date-picker';
import type EuiSwitch from './components/eui-switch';
import type EuiTab from './components/eui-tab';
import type EuiTabbedContent from './components/eui-tabbed-content';
import type EuiTabs from './components/eui-tabs';
import type EuiText from './components/eui-text';
import type EuiTextAlign from './components/eui-text-align';
import type EuiTextArea from './components/eui-text-area';
import type EuiTextColor from './components/eui-text-color';
import type EuiTitle from './components/eui-title';
import type EuiToast from './components/eui-toast';
import type EuiToolTip from './components/eui-tool-tip';
import type EuiToolTipPopover from './components/eui-tool-tip-popover';
import type TextBlock from './components/text-block';
import type argOrDefault from './helpers/arg-or-default';
import type castTo from './helpers/cast-to';
import type classNames from './helpers/class-names';
import type getEuiConfig from './helpers/get-eui-config';
import type inlineStyles from './helpers/inline-styles';
import type isColorDark from './helpers/is-color-dark';
import type useState from './helpers/use-state';
import type mutationObserver from './modifiers/mutation-observer';
import type outsideClickDetector from './modifiers/outside-click-detector';
import type resizeObserver from './modifiers/resize-observer';
import type screenReaderOnly from './modifiers/screen-reader-only';
import type simpleStyle from './modifiers/simple-style';
import type validatableControl from './modifiers/validatable-control';

export default interface EmberEuiRegistry {
  EuiButton: typeof EuiButton;
  'eui-button': typeof EuiButton;
  EuiButtonEmpty: typeof EuiButtonEmpty;
  'eui-button-empty': typeof EuiButtonEmpty;
  EuiAccordion: typeof EuiAccordion;
  'eui-accordion': typeof EuiAccordion;
  EuiAutoSizer: typeof EuiAutoSizer;
  'eui-auto-sizer': typeof EuiAutoSizer;
  EuiAvatar: typeof EuiAvatar;
  'eui-avatar': typeof EuiAvatar;
  EuiBadge: typeof EuiBadge;
  'eui-badge': typeof EuiBadge;
  EuiBetaBadge: typeof EuiBetaBadge;
  'eui-beta-badge': typeof EuiBetaBadge;
  EuiBreadcrumbs: typeof EuiBreadcrumbs;
  'eui-breadcrumbs': typeof EuiBreadcrumbs;
  EuiBadgeGroup: typeof EuiBadgeGroup;
  'eui-badge-group': typeof EuiBadgeGroup;
  EuiBottomBar: typeof EuiBottomBar;
  'eui-bottom-bar': typeof EuiBottomBar;
  EuiButtonGroup: typeof EuiButtonGroup;
  'eui-button-group': typeof EuiButtonGroup;
  EuiButtonIcon: typeof EuiButtonIcon;
  'eui-button-icon': typeof EuiButtonIcon;
  EuiCallOut: typeof EuiCallOut;
  'eui-call-out': typeof EuiCallOut;
  EuiCardSelect: typeof EuiCardSelect;
  'eui-card-select': typeof EuiCardSelect;
  EuiCheckbox: typeof EuiCheckbox;
  'eui-checkbox': typeof EuiCheckbox;
  EuiCode: typeof EuiCode;
  'eui-code': typeof EuiCode;
  EuiCodeBlock: typeof EuiCodeBlock;
  'eui-code-block': typeof EuiCodeBlock;
  EuiCard: typeof EuiCard;
  'eui-card': typeof EuiCard;
  EuiCheckableCard: typeof EuiCheckableCard;
  'eui-checkable-card': typeof EuiCheckableCard;
  EuiCheckboxGroup: typeof EuiCheckboxGroup;
  'eui-checkbox-group': typeof EuiCheckboxGroup;
  EuiCollapsibleNav: typeof EuiCollapsibleNav;
  'eui-collapsible-nav': typeof EuiCollapsibleNav;
  EuiComboBoxPill: typeof EuiComboBoxPill;
  'eui-combo-box-pill': typeof EuiComboBoxPill;
  EuiComboBox: typeof EuiComboBox;
  'eui-combo-box': typeof EuiComboBox;
  EuiCommentList: typeof EuiCommentList;
  'eui-comment-list': typeof EuiCommentList;
  EuiComment: typeof EuiComment;
  'eui-comment': typeof EuiComment;
  EuiConfirmModal: typeof EuiConfirmModal;
  'eui-confirm-modal': typeof EuiConfirmModal;
  EuiContextMenuItem: typeof EuiContextMenuItem;
  'eui-context-menu-item': typeof EuiContextMenuItem;
  EuiContextMenuPanel: typeof EuiContextMenuPanel;
  'eui-context-menu-panel': typeof EuiContextMenuPanel;
  EuiCopy: typeof EuiCopy;
  'eui-copy': typeof EuiCopy;
  EuiDescribedFormGroup: typeof EuiDescribedFormGroup;
  'eui-described-form-group': typeof EuiDescribedFormGroup;
  EuiDescriptionList: typeof EuiDescriptionList;
  'eui-description-list': typeof EuiDescriptionList;
  EuiDescriptionListTitle: typeof EuiDescriptionListTitle;
  'eui-description-list-title': typeof EuiDescriptionListTitle;
  EuiDescriptionListDescription: typeof EuiDescriptionListDescription;
  'eui-description-list-description': typeof EuiDescriptionListDescription;
  EuiDualRange: typeof EuiDualRange;
  'eui-dual-range': typeof EuiDualRange;
  EuiEmptyPrompt: typeof EuiEmptyPrompt;
  'eui-empty-prompt': typeof EuiEmptyPrompt;
  EuiFieldNumber: typeof EuiFieldNumber;
  'eui-field-number': typeof EuiFieldNumber;
  EuiFieldPassword: typeof EuiFieldPassword;
  'eui-field-password': typeof EuiFieldPassword;
  EuiFieldSearch: typeof EuiFieldSearch;
  'eui-field-search': typeof EuiFieldSearch;
  EuiFieldText: typeof EuiFieldText;
  'eui-field-text': typeof EuiFieldText;
  EuiTextArea: typeof EuiTextArea;
  'eui-text-area': typeof EuiTextArea;
  EuiFilePicker: typeof EuiFilePicker;
  'eui-file-picker': typeof EuiFilePicker;
  EuiFlexGrid: typeof EuiFlexGrid;
  'eui-flex-grid': typeof EuiFlexGrid;
  EuiFlexGroup: typeof EuiFlexGroup;
  'eui-flex-group': typeof EuiFlexGroup;
  EuiFlexItem: typeof EuiFlexItem;
  'eui-flex-item': typeof EuiFlexItem;
  EuiFlyout: typeof EuiFlyout;
  'eui-flyout': typeof EuiFlyout;
  EuiFlyoutBody: typeof EuiFlyoutBody;
  'eui-flyout-body': typeof EuiFlyoutBody;
  EuiFlyoutFooter: typeof EuiFlyoutFooter;
  'eui-flyout-footer': typeof EuiFlyoutFooter;
  EuiFlyoutHeader: typeof EuiFlyoutHeader;
  'eui-flyout-header': typeof EuiFlyoutHeader;
  EuiForm: typeof EuiForm;
  'eui-form': typeof EuiForm;
  EuiFormControlLayout: typeof EuiFormControlLayout;
  'eui-form-control-layout': typeof EuiFormControlLayout;
  EuiFormControlLayoutDelimited: typeof EuiFormControlLayoutDelimited;
  'eui-form-control-layout-delimited': typeof EuiFormControlLayoutDelimited;
  EuiFormControlLayoutIcons: typeof EuiFormControlLayoutIcons;
  'eui-form-control-layout-icons': typeof EuiFormControlLayoutIcons;
  EuiFormErrorText: typeof EuiFormErrorText;
  'eui-form-error-text': typeof EuiFormErrorText;
  EuiFormHelpText: typeof EuiFormHelpText;
  'eui-form-help-text': typeof EuiFormHelpText;
  EuiFormLabel: typeof EuiFormLabel;
  'eui-form-label': typeof EuiFormLabel;
  EuiFormRow: typeof EuiFormRow;
  'eui-form-row': typeof EuiFormRow;
  EuiHeader: typeof EuiHeader;
  'eui-header': typeof EuiHeader;
  EuiHeaderAlert: typeof EuiHeaderAlert;
  'eui-header-alert': typeof EuiHeaderAlert;
  EuiHeaderBreadcrumbs: typeof EuiHeaderBreadcrumbs;
  'eui-header-breadcrumbs': typeof EuiHeaderBreadcrumbs;
  EuiHeaderLink: typeof EuiHeaderLink;
  'eui-header-link': typeof EuiHeaderLink;
  EuiHeaderLinks: typeof EuiHeaderLinks;
  'eui-header-links': typeof EuiHeaderLinks;
  EuiHeaderLogo: typeof EuiHeaderLogo;
  'eui-header-logo': typeof EuiHeaderLogo;
  EuiHeaderSection: typeof EuiHeaderSection;
  'eui-header-section': typeof EuiHeaderSection;
  EuiHeaderSectionItem: typeof EuiHeaderSectionItem;
  'eui-header-section-item': typeof EuiHeaderSectionItem;
  EuiHeaderSectionItemButton: typeof EuiHeaderSectionItemButton;
  'eui-header-section-item-button': typeof EuiHeaderSectionItemButton;
  EuiHealth: typeof EuiHealth;
  'eui-health': typeof EuiHealth;
  EuiHideFor: typeof EuiHideFor;
  'eui-hide-for': typeof EuiHideFor;
  EuiHorizontalRule: typeof EuiHorizontalRule;
  'eui-horizontal-rule': typeof EuiHorizontalRule;
  EuiIcon: typeof EuiIcon;
  'eui-icon': typeof EuiIcon;
  EuiIconTip: typeof EuiIconTip;
  'eui-icon-tip': typeof EuiIconTip;
  EuiImage: typeof EuiImage;
  'eui-image': typeof EuiImage;
  EuiKeyPadMenu: typeof EuiKeyPadMenu;
  'eui-key-pad-menu': typeof EuiKeyPadMenu;
  EuiKeyPadMenuItem: typeof EuiKeyPadMenuItem;
  'eui-key-pad-menu-item': typeof EuiKeyPadMenuItem;
  EuiLink: typeof EuiLink;
  'eui-link': typeof EuiLink;
  EuiListGroupItem: typeof EuiListGroupItem;
  'eui-list-group-item': typeof EuiListGroupItem;
  EuiListGroup: typeof EuiListGroup;
  'eui-list-group': typeof EuiListGroup;
  EuiLoadingContent: typeof EuiLoadingContent;
  'eui-loading-content': typeof EuiLoadingContent;
  EuiLoadingLogo: typeof EuiLoadingLogo;
  'eui-loading-logo': typeof EuiLoadingLogo;
  EuiLoadingSpinner: typeof EuiLoadingSpinner;
  'eui-loading-spinner': typeof EuiLoadingSpinner;
  EuiModal: typeof EuiModal;
  'eui-modal': typeof EuiModal;
  EuiModalBody: typeof EuiModalBody;
  'eui-modal-body': typeof EuiModalBody;
  EuiModalFooter: typeof EuiModalFooter;
  'eui-modal-footer': typeof EuiModalFooter;
  EuiModalHeader: typeof EuiModalHeader;
  'eui-modal-header': typeof EuiModalHeader;
  EuiModalHeaderTitle: typeof EuiModalHeaderTitle;
  'eui-modal-header-title': typeof EuiModalHeaderTitle;
  EuiMarkdownEditor: typeof EuiMarkdownEditor;
  'eui-markdown-editor': typeof EuiMarkdownEditor;
  EuiMarkdownFormat: typeof EuiMarkdownFormat;
  'eui-markdown-format': typeof EuiMarkdownFormat;
  EuiNotificationBadge: typeof EuiNotificationBadge;
  'eui-notification-badge': typeof EuiNotificationBadge;
  EuiOverlayMask: typeof EuiOverlayMask;
  'eui-overlay-mask': typeof EuiOverlayMask;
  EuiPage: typeof EuiPage;
  'eui-page': typeof EuiPage;
  EuiPageBody: typeof EuiPageBody;
  'eui-page-body': typeof EuiPageBody;
  EuiPageContent: typeof EuiPageContent;
  'eui-page-content': typeof EuiPageContent;
  EuiPageContentBody: typeof EuiPageContentBody;
  'eui-page-content-body': typeof EuiPageContentBody;
  EuiPageContentHeader: typeof EuiPageContentHeader;
  'eui-page-content-header': typeof EuiPageContentHeader;
  EuiPageContentHeaderSection: typeof EuiPageContentHeaderSection;
  'eui-page-content-header-section': typeof EuiPageContentHeaderSection;
  EuiPageHeader: typeof EuiPageHeader;
  'eui-page-header': typeof EuiPageHeader;
  EuiPageHeaderSection: typeof EuiPageHeaderSection;
  'eui-page-header-section': typeof EuiPageHeaderSection;
  EuiPageSideBar: typeof EuiPageSideBar;
  'eui-page-side-bar': typeof EuiPageSideBar;
  EuiPagination: typeof EuiPagination;
  'eui-pagination': typeof EuiPagination;
  EuiPanel: typeof EuiPanel;
  'eui-panel': typeof EuiPanel;
  EuiPopover: typeof EuiPopover;
  'eui-popover': typeof EuiPopover;
  EuiPopoverTitle: typeof EuiPopoverTitle;
  'eui-popover-title': typeof EuiPopoverTitle;
  EuiPopoverFooter: typeof EuiPopoverFooter;
  'eui-popover-footer': typeof EuiPopoverFooter;
  EuiPortal: typeof EuiPortal;
  'eui-portal': typeof EuiPortal;
  EuiProgress: typeof EuiProgress;
  'eui-progress': typeof EuiProgress;
  EuiRange: typeof EuiRange;
  'eui-range': typeof EuiRange;
  EuiNotificationEvent: typeof EuiNotificationEvent;
  'eui-notification-event': typeof EuiNotificationEvent;
  EuiNotificationEventMessages: typeof EuiNotificationEventMessages;
  'eui-notification-event-messages': typeof EuiNotificationEventMessages;
  EuiNotificationEventMeta: typeof EuiNotificationEventMeta;
  'eui-notification-event-meta': typeof EuiNotificationEventMeta;
  EuiNotificationEventReadButton: typeof EuiNotificationEventReadButton;
  'eui-notification-event-read-button': typeof EuiNotificationEventReadButton;
  EuiNotificationEventReadIcon: typeof EuiNotificationEventReadIcon;
  'eui-notification-event-read-icon': typeof EuiNotificationEventReadIcon;
  EuiPageTemplate: typeof EuiPageTemplate;
  'eui-page-template': typeof EuiPageTemplate;
  EuiPaginationButton: typeof EuiPaginationButton;
  'eui-pagination-button': typeof EuiPaginationButton;
  EuiRangeHighlight: typeof EuiRangeHighlight;
  'eui-range-highlight': typeof EuiRangeHighlight;
  EuiRangeInput: typeof EuiRangeInput;
  'eui-range-input': typeof EuiRangeInput;
  EuiRangeLabel: typeof EuiRangeLabel;
  'eui-range-label': typeof EuiRangeLabel;
  EuiRangeLevels: typeof EuiRangeLevels;
  'eui-range-levels': typeof EuiRangeLevels;
  EuiRangeSlider: typeof EuiRangeSlider;
  'eui-range-slider': typeof EuiRangeSlider;
  EuiRangeThumb: typeof EuiRangeThumb;
  'eui-range-thumb': typeof EuiRangeThumb;
  EuiRangeTicks: typeof EuiRangeTicks;
  'eui-range-ticks': typeof EuiRangeTicks;
  EuiRadio: typeof EuiRadio;
  'eui-radio': typeof EuiRadio;
  EuiRadioGroup: typeof EuiRadioGroup;
  'eui-radio-group': typeof EuiRadioGroup;
  EuiRangeTooltip: typeof EuiRangeTooltip;
  'eui-range-tooltip': typeof EuiRangeTooltip;
  EuiRangeTrack: typeof EuiRangeTrack;
  'eui-range-track': typeof EuiRangeTrack;
  EuiRangeWrapper: typeof EuiRangeWrapper;
  'eui-range-wrapper': typeof EuiRangeWrapper;
  EuiSelect: typeof EuiSelect;
  'eui-select': typeof EuiSelect;
  EuiSelectableListItem: typeof EuiSelectableListItem;
  'eui-selectable-list-item': typeof EuiSelectableListItem;
  EuiShowFor: typeof EuiShowFor;
  'eui-show-for': typeof EuiShowFor;
  EuiSideNav: typeof EuiSideNav;
  'eui-side-nav': typeof EuiSideNav;
  EuiSpacer: typeof EuiSpacer;
  'eui-spacer': typeof EuiSpacer;
  EuiStat: typeof EuiStat;
  'eui-stat': typeof EuiStat;
  EuiStep: typeof EuiStep;
  'eui-step': typeof EuiStep;
  EuiSteps: typeof EuiSteps;
  'eui-steps': typeof EuiSteps;
  EuiStepHorizontal: typeof EuiStepHorizontal;
  'eui-step-horizontal': typeof EuiStepHorizontal;
  EuiStepNumber: typeof EuiStepNumber;
  'eui-step-number': typeof EuiStepNumber;
  EuiSubSteps: typeof EuiSubSteps;
  'eui-sub-steps': typeof EuiSubSteps;
  EuiSuperDatePicker: typeof EuiSuperDatePicker;
  'eui-super-date-picker': typeof EuiSuperDatePicker;
  EuiSwitch: typeof EuiSwitch;
  'eui-switch': typeof EuiSwitch;
  EuiTab: typeof EuiTab;
  'eui-tab': typeof EuiTab;
  EuiTabbedContent: typeof EuiTabbedContent;
  'eui-tabbed-content': typeof EuiTabbedContent;
  EuiTabs: typeof EuiTabs;
  'eui-tabs': typeof EuiTabs;
  EuiTextAlign: typeof EuiTextAlign;
  'eui-text-align': typeof EuiTextAlign;
  EuiTextColor: typeof EuiTextColor;
  'eui-text-color': typeof EuiTextColor;
  EuiText: typeof EuiText;
  'eui-text': typeof EuiText;
  EuiToast: typeof EuiToast;
  'eui-toast': typeof EuiToast;
  EuiTitle: typeof EuiTitle;
  'eui-title': typeof EuiTitle;
  EuiToolTipPopover: typeof EuiToolTipPopover;
  'eui-tool-tip-popover': typeof EuiToolTipPopover;
  EuiToolTip: typeof EuiToolTip;
  'eui-tool-tip': typeof EuiToolTip;
  EuiGlobalToastList: typeof EuiGlobalToastList;
  'eui-global-toast-list': typeof EuiGlobalToastList;
  TextBlock: typeof TextBlock;
  'text-block': typeof TextBlock;
  'arg-or-default': typeof argOrDefault;
  'cast-to': typeof castTo;
  'class-names': typeof classNames;
  'inline-styles': typeof inlineStyles;
  'is-color-dark': typeof isColorDark;
  'use-state': typeof useState;
  'get-eui-config': typeof getEuiConfig;
  'mutation-observer': typeof mutationObserver;
  'outside-click-detector': typeof outsideClickDetector;
  'resize-observer': typeof resizeObserver;
  'screen-reader-only': typeof screenReaderOnly;
  'simple-style': typeof simpleStyle;
  'validatable-control': typeof validatableControl;
}
