// GENERATED by scripts/generate-icons.mjs, do not edit by hand.
import icon0 from '../../vendor/icon/svgs/accessibility.svg?unsafe-inline';
import icon1 from '../../vendor/icon/svgs/app_add_data.svg?unsafe-inline';
import icon2 from '../../vendor/icon/svgs/app_advanced_settings.svg?unsafe-inline';
import icon3 from '../../vendor/icon/svgs/app_fleet.svg?unsafe-inline';
import icon4 from '../../vendor/icon/svgs/aggregate.svg?unsafe-inline';
import icon5 from '../../vendor/icon/svgs/analyzeEvent.svg?unsafe-inline';
import icon6 from '../../vendor/icon/svgs/annotation.svg?unsafe-inline';
import icon7 from '../../vendor/icon/svgs/app_apm.svg?unsafe-inline';
import icon8 from '../../vendor/icon/svgs/apm_trace.svg?unsafe-inline';
import icon9 from '../../vendor/icon/svgs/app_app_search.svg?unsafe-inline';
import icon10 from '../../vendor/icon/svgs/apps.svg?unsafe-inline';
import icon11 from '../../vendor/icon/svgs/arrow_down.svg?unsafe-inline';
import icon12 from '../../vendor/icon/svgs/arrow_left.svg?unsafe-inline';
import icon13 from '../../vendor/icon/svgs/arrow_right.svg?unsafe-inline';
import icon14 from '../../vendor/icon/svgs/arrow_up.svg?unsafe-inline';
import icon15 from '../../vendor/icon/svgs/arrowStart.svg?unsafe-inline';
import icon16 from '../../vendor/icon/svgs/arrowEnd.svg?unsafe-inline';
import icon17 from '../../vendor/icon/svgs/article.svg?unsafe-inline';
import icon18 from '../../vendor/icon/svgs/asterisk.svg?unsafe-inline';
import icon19 from '../../vendor/icon/svgs/app_auditbeat.svg?unsafe-inline';
import icon20 from '../../vendor/icon/svgs/beaker.svg?unsafe-inline';
import icon21 from '../../vendor/icon/svgs/bell.svg?unsafe-inline';
import icon22 from '../../vendor/icon/svgs/bellSlash.svg?unsafe-inline';
import icon23 from '../../vendor/icon/svgs/beta.svg?unsafe-inline';
import icon24 from '../../vendor/icon/svgs/bolt.svg?unsafe-inline';
import icon25 from '../../vendor/icon/svgs/boxes_horizontal.svg?unsafe-inline';
import icon26 from '../../vendor/icon/svgs/boxes_vertical.svg?unsafe-inline';
import icon27 from '../../vendor/icon/svgs/branch.svg?unsafe-inline';
import icon28 from '../../vendor/icon/svgs/branchUser.svg?unsafe-inline';
import icon29 from '../../vendor/icon/svgs/broom.svg?unsafe-inline';
import icon30 from '../../vendor/icon/svgs/brush.svg?unsafe-inline';
import icon31 from '../../vendor/icon/svgs/bug.svg?unsafe-inline';
import icon32 from '../../vendor/icon/svgs/bullseye.svg?unsafe-inline';
import icon33 from '../../vendor/icon/svgs/calendar.svg?unsafe-inline';
import icon34 from '../../vendor/icon/svgs/app_canvas.svg?unsafe-inline';
import icon35 from '../../vendor/icon/svgs/app_cases.svg?unsafe-inline';
import icon36 from '../../vendor/icon/svgs/check.svg?unsafe-inline';
import icon37 from '../../vendor/icon/svgs/checkInCircleFilled.svg?unsafe-inline';
import icon38 from '../../vendor/icon/svgs/cheer.svg?unsafe-inline';
import icon39 from '../../vendor/icon/svgs/ml_classification_job.svg?unsafe-inline';
import icon40 from '../../vendor/icon/svgs/clock.svg?unsafe-inline';
import icon41 from '../../vendor/icon/svgs/cloudDrizzle.svg?unsafe-inline';
import icon42 from '../../vendor/icon/svgs/cloudStormy.svg?unsafe-inline';
import icon43 from '../../vendor/icon/svgs/cloudSunny.svg?unsafe-inline';
import icon44 from '../../vendor/icon/svgs/cluster.svg?unsafe-inline';
import icon45 from '../../vendor/icon/svgs/app_code.svg?unsafe-inline';
import icon46 from '../../vendor/icon/svgs/color.svg?unsafe-inline';
import icon47 from '../../vendor/icon/svgs/compute.svg?unsafe-inline';
import icon48 from '../../vendor/icon/svgs/console.svg?unsafe-inline';
import icon49 from '../../vendor/icon/svgs/app_console.svg?unsafe-inline';
import icon50 from '../../vendor/icon/svgs/container.svg?unsafe-inline';
import icon51 from '../../vendor/icon/svgs/continuityAbove.svg?unsafe-inline';
import icon52 from '../../vendor/icon/svgs/continuityAboveBelow.svg?unsafe-inline';
import icon53 from '../../vendor/icon/svgs/continuityBelow.svg?unsafe-inline';
import icon54 from '../../vendor/icon/svgs/continuityWithin.svg?unsafe-inline';
import icon55 from '../../vendor/icon/svgs/controls_horizontal.svg?unsafe-inline';
import icon56 from '../../vendor/icon/svgs/controls_vertical.svg?unsafe-inline';
import icon57 from '../../vendor/icon/svgs/copy.svg?unsafe-inline';
import icon58 from '../../vendor/icon/svgs/copy_clipboard.svg?unsafe-inline';
import icon59 from '../../vendor/icon/svgs/ml_create_advanced_job.svg?unsafe-inline';
import icon60 from '../../vendor/icon/svgs/ml_create_multi_metric_job.svg?unsafe-inline';
import icon61 from '../../vendor/icon/svgs/ml_create_population_job.svg?unsafe-inline';
import icon62 from '../../vendor/icon/svgs/ml_create_single_metric_job.svg?unsafe-inline';
import icon63 from '../../vendor/icon/svgs/cross.svg?unsafe-inline';
import icon64 from '../../vendor/icon/svgs/app_cross_cluster_replication.svg?unsafe-inline';
import icon65 from '../../vendor/icon/svgs/crosshairs.svg?unsafe-inline';
import icon66 from '../../vendor/icon/svgs/currency.svg?unsafe-inline';
import icon67 from '../../vendor/icon/svgs/cut.svg?unsafe-inline';
import icon68 from '../../vendor/icon/svgs/app_dashboard.svg?unsafe-inline';
import icon69 from '../../vendor/icon/svgs/ml_data_visualizer.svg?unsafe-inline';
import icon70 from '../../vendor/icon/svgs/database.svg?unsafe-inline';
import icon71 from '../../vendor/icon/svgs/desktop.svg?unsafe-inline';
import icon72 from '../../vendor/icon/svgs/app_devtools.svg?unsafe-inline';
import icon73 from '../../vendor/icon/svgs/app_discover.svg?unsafe-inline';
import icon74 from '../../vendor/icon/svgs/discuss.svg?unsafe-inline';
import icon75 from '../../vendor/icon/svgs/document.svg?unsafe-inline';
import icon76 from '../../vendor/icon/svgs/documentEdit.svg?unsafe-inline';
import icon77 from '../../vendor/icon/svgs/documentation.svg?unsafe-inline';
import icon78 from '../../vendor/icon/svgs/documents.svg?unsafe-inline';
import icon79 from '../../vendor/icon/svgs/dot.svg?unsafe-inline';
import icon80 from '../../vendor/icon/svgs/dotInCircle.svg?unsafe-inline';
import icon81 from '../../vendor/icon/svgs/doubleArrowLeft.svg?unsafe-inline';
import icon82 from '../../vendor/icon/svgs/doubleArrowRight.svg?unsafe-inline';
import icon83 from '../../vendor/icon/svgs/download.svg?unsafe-inline';
import icon84 from '../../vendor/icon/svgs/editor_align_center.svg?unsafe-inline';
import icon85 from '../../vendor/icon/svgs/editor_align_left.svg?unsafe-inline';
import icon86 from '../../vendor/icon/svgs/editor_align_right.svg?unsafe-inline';
import icon87 from '../../vendor/icon/svgs/editor_bold.svg?unsafe-inline';
import icon88 from '../../vendor/icon/svgs/editor_checklist.svg?unsafe-inline';
import icon89 from '../../vendor/icon/svgs/editor_code_block.svg?unsafe-inline';
import icon90 from '../../vendor/icon/svgs/editor_comment.svg?unsafe-inline';
import icon91 from '../../vendor/icon/svgs/editorDistributeHorizontal.svg?unsafe-inline';
import icon92 from '../../vendor/icon/svgs/editorDistributeVertical.svg?unsafe-inline';
import icon93 from '../../vendor/icon/svgs/editor_heading.svg?unsafe-inline';
import icon94 from '../../vendor/icon/svgs/editor_italic.svg?unsafe-inline';
import icon95 from '../../vendor/icon/svgs/editorItemAlignBottom.svg?unsafe-inline';
import icon96 from '../../vendor/icon/svgs/editorItemAlignCenter.svg?unsafe-inline';
import icon97 from '../../vendor/icon/svgs/editorItemAlignLeft.svg?unsafe-inline';
import icon98 from '../../vendor/icon/svgs/editorItemAlignMiddle.svg?unsafe-inline';
import icon99 from '../../vendor/icon/svgs/editorItemAlignRight.svg?unsafe-inline';
import icon100 from '../../vendor/icon/svgs/editorItemAlignTop.svg?unsafe-inline';
import icon101 from '../../vendor/icon/svgs/editor_link.svg?unsafe-inline';
import icon102 from '../../vendor/icon/svgs/editor_ordered_list.svg?unsafe-inline';
import icon103 from '../../vendor/icon/svgs/editorPositionBottomLeft.svg?unsafe-inline';
import icon104 from '../../vendor/icon/svgs/editorPositionBottomRight.svg?unsafe-inline';
import icon105 from '../../vendor/icon/svgs/editorPositionTopLeft.svg?unsafe-inline';
import icon106 from '../../vendor/icon/svgs/editorPositionTopRight.svg?unsafe-inline';
import icon107 from '../../vendor/icon/svgs/editor_redo.svg?unsafe-inline';
import icon108 from '../../vendor/icon/svgs/editor_strike.svg?unsafe-inline';
import icon109 from '../../vendor/icon/svgs/editor_table.svg?unsafe-inline';
import icon110 from '../../vendor/icon/svgs/editor_underline.svg?unsafe-inline';
import icon111 from '../../vendor/icon/svgs/editor_undo.svg?unsafe-inline';
import icon112 from '../../vendor/icon/svgs/editor_unordered_list.svg?unsafe-inline';
import icon113 from '../../vendor/icon/svgs/email.svg?unsafe-inline';
import icon114 from '../../vendor/icon/svgs/empty.svg?unsafe-inline';
import icon115 from '../../vendor/icon/svgs/app_ems.svg?unsafe-inline';
import icon116 from '../../vendor/icon/svgs/eql.svg?unsafe-inline';
import icon117 from '../../vendor/icon/svgs/eraser.svg?unsafe-inline';
import icon118 from '../../vendor/icon/svgs/error.svg?unsafe-inline';
import icon119 from '../../vendor/icon/svgs/exit.svg?unsafe-inline';
import icon120 from '../../vendor/icon/svgs/expand.svg?unsafe-inline';
import icon121 from '../../vendor/icon/svgs/expandMini.svg?unsafe-inline';
import icon122 from '../../vendor/icon/svgs/export.svg?unsafe-inline';
import icon123 from '../../vendor/icon/svgs/eye.svg?unsafe-inline';
import icon124 from '../../vendor/icon/svgs/eye_closed.svg?unsafe-inline';
import icon125 from '../../vendor/icon/svgs/face_happy.svg?unsafe-inline';
import icon126 from '../../vendor/icon/svgs/face_neutral.svg?unsafe-inline';
import icon127 from '../../vendor/icon/svgs/face_sad.svg?unsafe-inline';
import icon128 from '../../vendor/icon/svgs/app_filebeat.svg?unsafe-inline';
import icon129 from '../../vendor/icon/svgs/filter.svg?unsafe-inline';
import icon130 from '../../vendor/icon/svgs/filterExclude.svg?unsafe-inline';
import icon131 from '../../vendor/icon/svgs/filterIgnore.svg?unsafe-inline';
import icon132 from '../../vendor/icon/svgs/filterInclude.svg?unsafe-inline';
import icon133 from '../../vendor/icon/svgs/filterInCircle.svg?unsafe-inline';
import icon134 from '../../vendor/icon/svgs/flag.svg?unsafe-inline';
import icon135 from '../../vendor/icon/svgs/app_agent.svg?unsafe-inline';
import icon136 from '../../vendor/icon/svgs/fold.svg?unsafe-inline';
import icon137 from '../../vendor/icon/svgs/folder_check.svg?unsafe-inline';
import icon138 from '../../vendor/icon/svgs/folder_closed.svg?unsafe-inline';
import icon139 from '../../vendor/icon/svgs/folder_exclamation.svg?unsafe-inline';
import icon140 from '../../vendor/icon/svgs/folder_open.svg?unsafe-inline';
import icon141 from '../../vendor/icon/svgs/frameNext.svg?unsafe-inline';
import icon142 from '../../vendor/icon/svgs/framePrevious.svg?unsafe-inline';
import icon143 from '../../vendor/icon/svgs/full_screen.svg?unsafe-inline';
import icon144 from '../../vendor/icon/svgs/fullScreenExit.svg?unsafe-inline';
import icon145 from '../../vendor/icon/svgs/function.svg?unsafe-inline';
import icon146 from '../../vendor/icon/svgs/gear.svg?unsafe-inline';
import icon147 from '../../vendor/icon/svgs/app_gis.svg?unsafe-inline';
import icon148 from '../../vendor/icon/svgs/glasses.svg?unsafe-inline';
import icon149 from '../../vendor/icon/svgs/globe.svg?unsafe-inline';
import icon150 from '../../vendor/icon/svgs/grab.svg?unsafe-inline';
import icon151 from '../../vendor/icon/svgs/grab_horizontal.svg?unsafe-inline';
import icon152 from '../../vendor/icon/svgs/app_graph.svg?unsafe-inline';
import icon153 from '../../vendor/icon/svgs/grid.svg?unsafe-inline';
import icon154 from '../../vendor/icon/svgs/app_grok.svg?unsafe-inline';
import icon155 from '../../vendor/icon/svgs/heart.svg?unsafe-inline';
import icon156 from '../../vendor/icon/svgs/app_heartbeat.svg?unsafe-inline';
import icon157 from '../../vendor/icon/svgs/heatmap.svg?unsafe-inline';
import icon158 from '../../vendor/icon/svgs/help.svg?unsafe-inline';
import icon159 from '../../vendor/icon/svgs/home.svg?unsafe-inline';
import icon160 from '../../vendor/icon/svgs/iInCircle.svg?unsafe-inline';
import icon161 from '../../vendor/icon/svgs/image.svg?unsafe-inline';
import icon162 from '../../vendor/icon/svgs/import.svg?unsafe-inline';
import icon163 from '../../vendor/icon/svgs/index_close.svg?unsafe-inline';
import icon164 from '../../vendor/icon/svgs/index_edit.svg?unsafe-inline';
import icon165 from '../../vendor/icon/svgs/index_flush.svg?unsafe-inline';
import icon166 from '../../vendor/icon/svgs/app_index_management.svg?unsafe-inline';
import icon167 from '../../vendor/icon/svgs/index_mapping.svg?unsafe-inline';
import icon168 from '../../vendor/icon/svgs/index_open.svg?unsafe-inline';
import icon169 from '../../vendor/icon/svgs/app_index_pattern.svg?unsafe-inline';
import icon170 from '../../vendor/icon/svgs/app_index_rollup.svg?unsafe-inline';
import icon171 from '../../vendor/icon/svgs/index_runtime.svg?unsafe-inline';
import icon172 from '../../vendor/icon/svgs/index_settings.svg?unsafe-inline';
import icon173 from '../../vendor/icon/svgs/indexTemporary.svg?unsafe-inline';
import icon174 from '../../vendor/icon/svgs/infinity.svg?unsafe-inline';
import icon175 from '../../vendor/icon/svgs/inputOutput.svg?unsafe-inline';
import icon176 from '../../vendor/icon/svgs/inspect.svg?unsafe-inline';
import icon177 from '../../vendor/icon/svgs/invert.svg?unsafe-inline';
import icon178 from '../../vendor/icon/svgs/ip.svg?unsafe-inline';
import icon179 from '../../vendor/icon/svgs/keyboard.svg?unsafe-inline';
import icon180 from '../../vendor/icon/svgs/kql_field.svg?unsafe-inline';
import icon181 from '../../vendor/icon/svgs/kql_function.svg?unsafe-inline';
import icon182 from '../../vendor/icon/svgs/kql_operand.svg?unsafe-inline';
import icon183 from '../../vendor/icon/svgs/kql_selector.svg?unsafe-inline';
import icon184 from '../../vendor/icon/svgs/kql_value.svg?unsafe-inline';
import icon185 from '../../vendor/icon/svgs/kubernetesNode.svg?unsafe-inline';
import icon186 from '../../vendor/icon/svgs/kubernetesPod.svg?unsafe-inline';
import icon187 from '../../vendor/icon/svgs/launch.svg?unsafe-inline';
import icon188 from '../../vendor/icon/svgs/layers.svg?unsafe-inline';
import icon189 from '../../vendor/icon/svgs/app_lens.svg?unsafe-inline';
import icon190 from '../../vendor/icon/svgs/lettering.svg?unsafe-inline';
import icon191 from '../../vendor/icon/svgs/lineDashed.svg?unsafe-inline';
import icon192 from '../../vendor/icon/svgs/lineDotted.svg?unsafe-inline';
import icon193 from '../../vendor/icon/svgs/lineSolid.svg?unsafe-inline';
import icon194 from '../../vendor/icon/svgs/link.svg?unsafe-inline';
import icon195 from '../../vendor/icon/svgs/list.svg?unsafe-inline';
import icon196 from '../../vendor/icon/svgs/list_add.svg?unsafe-inline';
import icon197 from '../../vendor/icon/svgs/lock.svg?unsafe-inline';
import icon198 from '../../vendor/icon/svgs/lockOpen.svg?unsafe-inline';
import icon199 from '../../vendor/icon/svgs/logo_aws.svg?unsafe-inline';
import icon200 from '../../vendor/icon/svgs/logo_aws_mono.svg?unsafe-inline';
import icon201 from '../../vendor/icon/svgs/logo_aerospike.svg?unsafe-inline';
import icon202 from '../../vendor/icon/svgs/logo_apache.svg?unsafe-inline';
import icon203 from '../../vendor/icon/svgs/logo_app_search.svg?unsafe-inline';
import icon204 from '../../vendor/icon/svgs/logo_azure.svg?unsafe-inline';
import icon205 from '../../vendor/icon/svgs/logo_azure_mono.svg?unsafe-inline';
import icon206 from '../../vendor/icon/svgs/logo_beats.svg?unsafe-inline';
import icon207 from '../../vendor/icon/svgs/logo_business_analytics.svg?unsafe-inline';
import icon208 from '../../vendor/icon/svgs/logo_ceph.svg?unsafe-inline';
import icon209 from '../../vendor/icon/svgs/logo_cloud.svg?unsafe-inline';
import icon210 from '../../vendor/icon/svgs/logo_cloud_ece.svg?unsafe-inline';
import icon211 from '../../vendor/icon/svgs/logo_code.svg?unsafe-inline';
import icon212 from '../../vendor/icon/svgs/logo_codesandbox.svg?unsafe-inline';
import icon213 from '../../vendor/icon/svgs/logo_couchbase.svg?unsafe-inline';
import icon214 from '../../vendor/icon/svgs/logo_docker.svg?unsafe-inline';
import icon215 from '../../vendor/icon/svgs/logo_dropwizard.svg?unsafe-inline';
import icon216 from '../../vendor/icon/svgs/logo_elastic.svg?unsafe-inline';
import icon217 from '../../vendor/icon/svgs/logo_elastic_stack.svg?unsafe-inline';
import icon218 from '../../vendor/icon/svgs/logo_elasticsearch.svg?unsafe-inline';
import icon219 from '../../vendor/icon/svgs/logo_enterprise_search.svg?unsafe-inline';
import icon220 from '../../vendor/icon/svgs/logo_etcd.svg?unsafe-inline';
import icon221 from '../../vendor/icon/svgs/logo_gcp.svg?unsafe-inline';
import icon222 from '../../vendor/icon/svgs/logo_gcp_mono.svg?unsafe-inline';
import icon223 from '../../vendor/icon/svgs/logo_github.svg?unsafe-inline';
import icon224 from '../../vendor/icon/svgs/logo_gmail.svg?unsafe-inline';
import icon225 from '../../vendor/icon/svgs/logo_golang.svg?unsafe-inline';
import icon226 from '../../vendor/icon/svgs/logo_google_g.svg?unsafe-inline';
import icon227 from '../../vendor/icon/svgs/logo_haproxy.svg?unsafe-inline';
import icon228 from '../../vendor/icon/svgs/logo_ibm.svg?unsafe-inline';
import icon229 from '../../vendor/icon/svgs/logo_ibm_mono.svg?unsafe-inline';
import icon230 from '../../vendor/icon/svgs/logo_kafka.svg?unsafe-inline';
import icon231 from '../../vendor/icon/svgs/logo_kibana.svg?unsafe-inline';
import icon232 from '../../vendor/icon/svgs/logo_kubernetes.svg?unsafe-inline';
import icon233 from '../../vendor/icon/svgs/logo_logging.svg?unsafe-inline';
import icon234 from '../../vendor/icon/svgs/logo_logstash.svg?unsafe-inline';
import icon235 from '../../vendor/icon/svgs/logo_maps.svg?unsafe-inline';
import icon236 from '../../vendor/icon/svgs/logo_memcached.svg?unsafe-inline';
import icon237 from '../../vendor/icon/svgs/logo_metrics.svg?unsafe-inline';
import icon238 from '../../vendor/icon/svgs/logo_mongodb.svg?unsafe-inline';
import icon239 from '../../vendor/icon/svgs/logo_mysql.svg?unsafe-inline';
import icon240 from '../../vendor/icon/svgs/logo_nginx.svg?unsafe-inline';
import icon241 from '../../vendor/icon/svgs/logo_observability.svg?unsafe-inline';
import icon242 from '../../vendor/icon/svgs/logo_osquery.svg?unsafe-inline';
import icon243 from '../../vendor/icon/svgs/logo_php.svg?unsafe-inline';
import icon244 from '../../vendor/icon/svgs/logo_postgres.svg?unsafe-inline';
import icon245 from '../../vendor/icon/svgs/logo_prometheus.svg?unsafe-inline';
import icon246 from '../../vendor/icon/svgs/logo_rabbitmq.svg?unsafe-inline';
import icon247 from '../../vendor/icon/svgs/logo_redis.svg?unsafe-inline';
import icon248 from '../../vendor/icon/svgs/logo_security.svg?unsafe-inline';
import icon249 from '../../vendor/icon/svgs/logo_site_search.svg?unsafe-inline';
import icon250 from '../../vendor/icon/svgs/logo_sketch.svg?unsafe-inline';
import icon251 from '../../vendor/icon/svgs/logo_slack.svg?unsafe-inline';
import icon252 from '../../vendor/icon/svgs/logo_uptime.svg?unsafe-inline';
import icon253 from '../../vendor/icon/svgs/logo_vulnerability_management.svg?unsafe-inline';
import icon254 from '../../vendor/icon/svgs/logo_webhook.svg?unsafe-inline';
import icon255 from '../../vendor/icon/svgs/logo_windows.svg?unsafe-inline';
import icon256 from '../../vendor/icon/svgs/logo_workplace_search.svg?unsafe-inline';
import icon257 from '../../vendor/icon/svgs/app_logs.svg?unsafe-inline';
import icon258 from '../../vendor/icon/svgs/logstash_filter.svg?unsafe-inline';
import icon259 from '../../vendor/icon/svgs/logstash_if.svg?unsafe-inline';
import icon260 from '../../vendor/icon/svgs/logstash_input.svg?unsafe-inline';
import icon261 from '../../vendor/icon/svgs/logstash_output.svg?unsafe-inline';
import icon262 from '../../vendor/icon/svgs/logstash_queue.svg?unsafe-inline';
import icon263 from '../../vendor/icon/svgs/app_ml.svg?unsafe-inline';
import icon264 from '../../vendor/icon/svgs/magnet.svg?unsafe-inline';
import icon265 from '../../vendor/icon/svgs/magnifyWithExclamation.svg?unsafe-inline';
import icon266 from '../../vendor/icon/svgs/magnifyWithMinus.svg?unsafe-inline';
import icon267 from '../../vendor/icon/svgs/magnifyWithPlus.svg?unsafe-inline';
import icon268 from '../../vendor/icon/svgs/app_management.svg?unsafe-inline';
import icon269 from '../../vendor/icon/svgs/map_marker.svg?unsafe-inline';
import icon270 from '../../vendor/icon/svgs/memory.svg?unsafe-inline';
import icon271 from '../../vendor/icon/svgs/menu.svg?unsafe-inline';
import icon272 from '../../vendor/icon/svgs/menuDown.svg?unsafe-inline';
import icon273 from '../../vendor/icon/svgs/menuLeft.svg?unsafe-inline';
import icon274 from '../../vendor/icon/svgs/menuRight.svg?unsafe-inline';
import icon275 from '../../vendor/icon/svgs/menuUp.svg?unsafe-inline';
import icon276 from '../../vendor/icon/svgs/merge.svg?unsafe-inline';
import icon277 from '../../vendor/icon/svgs/app_metricbeat.svg?unsafe-inline';
import icon278 from '../../vendor/icon/svgs/app_metrics.svg?unsafe-inline';
import icon279 from '../../vendor/icon/svgs/minimize.svg?unsafe-inline';
import icon280 from '../../vendor/icon/svgs/minus.svg?unsafe-inline';
import icon281 from '../../vendor/icon/svgs/minus_in_circle.svg?unsafe-inline';
import icon282 from '../../vendor/icon/svgs/minus_in_circle_filled.svg?unsafe-inline';
import icon283 from '../../vendor/icon/svgs/mobile.svg?unsafe-inline';
import icon284 from '../../vendor/icon/svgs/app_monitoring.svg?unsafe-inline';
import icon285 from '../../vendor/icon/svgs/moon.svg?unsafe-inline';
import icon286 from '../../vendor/icon/svgs/namespace.svg?unsafe-inline';
import icon287 from '../../vendor/icon/svgs/nested.svg?unsafe-inline';
import icon288 from '../../vendor/icon/svgs/node.svg?unsafe-inline';
import icon289 from '../../vendor/icon/svgs/app_notebook.svg?unsafe-inline';
import icon290 from '../../vendor/icon/svgs/number.svg?unsafe-inline';
import icon291 from '../../vendor/icon/svgs/offline.svg?unsafe-inline';
import icon292 from '../../vendor/icon/svgs/online.svg?unsafe-inline';
import icon293 from '../../vendor/icon/svgs/ml_outlier_detection_job.svg?unsafe-inline';
import icon294 from '../../vendor/icon/svgs/package.svg?unsafe-inline';
import icon295 from '../../vendor/icon/svgs/app_packetbeat.svg?unsafe-inline';
import icon296 from '../../vendor/icon/svgs/pageSelect.svg?unsafe-inline';
import icon297 from '../../vendor/icon/svgs/pagesSelect.svg?unsafe-inline';
import icon298 from '../../vendor/icon/svgs/paper_clip.svg?unsafe-inline';
import icon299 from '../../vendor/icon/svgs/partial.svg?unsafe-inline';
import icon300 from '../../vendor/icon/svgs/pause.svg?unsafe-inline';
import icon301 from '../../vendor/icon/svgs/payment.svg?unsafe-inline';
import icon302 from '../../vendor/icon/svgs/pencil.svg?unsafe-inline';
import icon303 from '../../vendor/icon/svgs/percent.svg?unsafe-inline';
import icon304 from '../../vendor/icon/svgs/pin.svg?unsafe-inline';
import icon305 from '../../vendor/icon/svgs/pin_filled.svg?unsafe-inline';
import icon306 from '../../vendor/icon/svgs/app_pipeline.svg?unsafe-inline';
import icon307 from '../../vendor/icon/svgs/pivot.svg?unsafe-inline';
import icon308 from '../../vendor/icon/svgs/play.svg?unsafe-inline';
import icon309 from '../../vendor/icon/svgs/playFilled.svg?unsafe-inline';
import icon310 from '../../vendor/icon/svgs/plus.svg?unsafe-inline';
import icon311 from '../../vendor/icon/svgs/plus_in_circle.svg?unsafe-inline';
import icon312 from '../../vendor/icon/svgs/plus_in_circle_filled.svg?unsafe-inline';
import icon313 from '../../vendor/icon/svgs/popout.svg?unsafe-inline';
import icon314 from '../../vendor/icon/svgs/push.svg?unsafe-inline';
import icon315 from '../../vendor/icon/svgs/question_in_circle.svg?unsafe-inline';
import icon316 from '../../vendor/icon/svgs/quote.svg?unsafe-inline';
import icon317 from '../../vendor/icon/svgs/app_recently_viewed.svg?unsafe-inline';
import icon318 from '../../vendor/icon/svgs/refresh.svg?unsafe-inline';
import icon319 from '../../vendor/icon/svgs/ml_regression_job.svg?unsafe-inline';
import icon320 from '../../vendor/icon/svgs/reporter.svg?unsafe-inline';
import icon321 from '../../vendor/icon/svgs/app_reporting.svg?unsafe-inline';
import icon322 from '../../vendor/icon/svgs/return_key.svg?unsafe-inline';
import icon323 from '../../vendor/icon/svgs/save.svg?unsafe-inline';
import icon324 from '../../vendor/icon/svgs/app_saved_objects.svg?unsafe-inline';
import icon325 from '../../vendor/icon/svgs/scale.svg?unsafe-inline';
import icon326 from '../../vendor/icon/svgs/search.svg?unsafe-inline';
import icon327 from '../../vendor/icon/svgs/app_search_profiler.svg?unsafe-inline';
import icon328 from '../../vendor/icon/svgs/app_security_analytics.svg?unsafe-inline';
import icon329 from '../../vendor/icon/svgs/app_security.svg?unsafe-inline';
import icon330 from '../../vendor/icon/svgs/securitySignal.svg?unsafe-inline';
import icon331 from '../../vendor/icon/svgs/securitySignalDetected.svg?unsafe-inline';
import icon332 from '../../vendor/icon/svgs/securitySignalResolved.svg?unsafe-inline';
import icon333 from '../../vendor/icon/svgs/sessionViewer.svg?unsafe-inline';
import icon334 from '../../vendor/icon/svgs/shard.svg?unsafe-inline';
import icon335 from '../../vendor/icon/svgs/share.svg?unsafe-inline';
import icon336 from '../../vendor/icon/svgs/snowflake.svg?unsafe-inline';
import icon337 from '../../vendor/icon/svgs/sortAscending.svg?unsafe-inline';
import icon338 from '../../vendor/icon/svgs/sortDescending.svg?unsafe-inline';
import icon339 from '../../vendor/icon/svgs/sort_down.svg?unsafe-inline';
import icon340 from '../../vendor/icon/svgs/sortLeft.svg?unsafe-inline';
import icon341 from '../../vendor/icon/svgs/sortRight.svg?unsafe-inline';
import icon342 from '../../vendor/icon/svgs/sort_up.svg?unsafe-inline';
import icon343 from '../../vendor/icon/svgs/sortable.svg?unsafe-inline';
import icon344 from '../../vendor/icon/svgs/spaces.svg?unsafe-inline';
import icon345 from '../../vendor/icon/svgs/app_spaces.svg?unsafe-inline';
import icon346 from '../../vendor/icon/svgs/app_sql.svg?unsafe-inline';
import icon347 from '../../vendor/icon/svgs/star_empty.svg?unsafe-inline';
import icon348 from '../../vendor/icon/svgs/star_empty_space.svg?unsafe-inline';
import icon349 from '../../vendor/icon/svgs/star_filled.svg?unsafe-inline';
import icon350 from '../../vendor/icon/svgs/star_filled_space.svg?unsafe-inline';
import icon351 from '../../vendor/icon/svgs/star_minus_empty.svg?unsafe-inline';
import icon352 from '../../vendor/icon/svgs/star_minus_filled.svg?unsafe-inline';
import icon353 from '../../vendor/icon/svgs/starPlusEmpty.svg?unsafe-inline';
import icon354 from '../../vendor/icon/svgs/starPlusFilled.svg?unsafe-inline';
import icon355 from '../../vendor/icon/svgs/stats.svg?unsafe-inline';
import icon356 from '../../vendor/icon/svgs/stop.svg?unsafe-inline';
import icon357 from '../../vendor/icon/svgs/stop_filled.svg?unsafe-inline';
import icon358 from '../../vendor/icon/svgs/stop_slash.svg?unsafe-inline';
import icon359 from '../../vendor/icon/svgs/storage.svg?unsafe-inline';
import icon360 from '../../vendor/icon/svgs/string.svg?unsafe-inline';
import icon361 from '../../vendor/icon/svgs/submodule.svg?unsafe-inline';
import icon362 from '../../vendor/icon/svgs/sun.svg?unsafe-inline';
import icon363 from '../../vendor/icon/svgs/swatch_input.svg?unsafe-inline';
import icon364 from '../../vendor/icon/svgs/symlink.svg?unsafe-inline';
import icon365 from '../../vendor/icon/svgs/table_density_compact.svg?unsafe-inline';
import icon366 from '../../vendor/icon/svgs/table_density_expanded.svg?unsafe-inline';
import icon367 from '../../vendor/icon/svgs/table_density_normal.svg?unsafe-inline';
import icon368 from '../../vendor/icon/svgs/tableOfContents.svg?unsafe-inline';
import icon369 from '../../vendor/icon/svgs/tag.svg?unsafe-inline';
import icon370 from '../../vendor/icon/svgs/tear.svg?unsafe-inline';
import icon371 from '../../vendor/icon/svgs/temperature.svg?unsafe-inline';
import icon372 from '../../vendor/icon/svgs/timeline.svg?unsafe-inline';
import icon373 from '../../vendor/icon/svgs/timelineWithArrow.svg?unsafe-inline';
import icon374 from '../../vendor/icon/svgs/app_timelion.svg?unsafe-inline';
import icon375 from '../../vendor/icon/svgs/timeRefresh.svg?unsafe-inline';
import icon376 from '../../vendor/icon/svgs/timeslider.svg?unsafe-inline';
import icon377 from '../../vendor/icon/svgs/training.svg?unsafe-inline';
import icon378 from '../../vendor/icon/svgs/trash.svg?unsafe-inline';
import icon379 from '../../vendor/icon/svgs/unfold.svg?unsafe-inline';
import icon380 from '../../vendor/icon/svgs/unlink.svg?unsafe-inline';
import icon381 from '../../vendor/icon/svgs/app_upgrade_assistant.svg?unsafe-inline';
import icon382 from '../../vendor/icon/svgs/app_uptime.svg?unsafe-inline';
import icon383 from '../../vendor/icon/svgs/user.svg?unsafe-inline';
import icon384 from '../../vendor/icon/svgs/userAvatar.svg?unsafe-inline';
import icon385 from '../../vendor/icon/svgs/users.svg?unsafe-inline';
import icon386 from '../../vendor/icon/svgs/app_users_roles.svg?unsafe-inline';
import icon387 from '../../vendor/icon/svgs/vector.svg?unsafe-inline';
import icon388 from '../../vendor/icon/svgs/videoPlayer.svg?unsafe-inline';
import icon389 from '../../vendor/icon/svgs/vis_area.svg?unsafe-inline';
import icon390 from '../../vendor/icon/svgs/vis_area_stacked.svg?unsafe-inline';
import icon391 from '../../vendor/icon/svgs/vis_bar_horizontal.svg?unsafe-inline';
import icon392 from '../../vendor/icon/svgs/vis_bar_horizontal_stacked.svg?unsafe-inline';
import icon393 from '../../vendor/icon/svgs/vis_bar_vertical.svg?unsafe-inline';
import icon394 from '../../vendor/icon/svgs/vis_bar_vertical_stacked.svg?unsafe-inline';
import icon395 from '../../vendor/icon/svgs/vis_gauge.svg?unsafe-inline';
import icon396 from '../../vendor/icon/svgs/vis_goal.svg?unsafe-inline';
import icon397 from '../../vendor/icon/svgs/vis_line.svg?unsafe-inline';
import icon398 from '../../vendor/icon/svgs/vis_map_coordinate.svg?unsafe-inline';
import icon399 from '../../vendor/icon/svgs/vis_map_region.svg?unsafe-inline';
import icon400 from '../../vendor/icon/svgs/vis_metric.svg?unsafe-inline';
import icon401 from '../../vendor/icon/svgs/vis_pie.svg?unsafe-inline';
import icon402 from '../../vendor/icon/svgs/vis_table.svg?unsafe-inline';
import icon403 from '../../vendor/icon/svgs/vis_tag_cloud.svg?unsafe-inline';
import icon404 from '../../vendor/icon/svgs/vis_text.svg?unsafe-inline';
import icon405 from '../../vendor/icon/svgs/vis_timelion.svg?unsafe-inline';
import icon406 from '../../vendor/icon/svgs/vis_vega.svg?unsafe-inline';
import icon407 from '../../vendor/icon/svgs/vis_visual_builder.svg?unsafe-inline';
import icon408 from '../../vendor/icon/svgs/app_visualize.svg?unsafe-inline';
import icon409 from '../../vendor/icon/svgs/app_vulnerability_management.svg?unsafe-inline';
import icon410 from '../../vendor/icon/svgs/warning.svg?unsafe-inline';
import icon411 from '../../vendor/icon/svgs/app_watches.svg?unsafe-inline';
import icon412 from '../../vendor/icon/svgs/wordWrap.svg?unsafe-inline';
import icon413 from '../../vendor/icon/svgs/wordWrapDisabled.svg?unsafe-inline';
import icon414 from '../../vendor/icon/svgs/app_workplace_search.svg?unsafe-inline';
import icon415 from '../../vendor/icon/svgs/wrench.svg?unsafe-inline';
import icon416 from '../../vendor/icon/svgs/tokens/tokenAlias.svg?unsafe-inline';
import icon417 from '../../vendor/icon/svgs/tokens/tokenAnnotation.svg?unsafe-inline';
import icon418 from '../../vendor/icon/svgs/tokens/tokenArray.svg?unsafe-inline';
import icon419 from '../../vendor/icon/svgs/tokens/tokenBinary.svg?unsafe-inline';
import icon420 from '../../vendor/icon/svgs/tokens/tokenBoolean.svg?unsafe-inline';
import icon421 from '../../vendor/icon/svgs/tokens/tokenClass.svg?unsafe-inline';
import icon422 from '../../vendor/icon/svgs/tokens/tokenCompletionSuggester.svg?unsafe-inline';
import icon423 from '../../vendor/icon/svgs/tokens/tokenConstant.svg?unsafe-inline';
import icon424 from '../../vendor/icon/svgs/tokens/tokenDate.svg?unsafe-inline';
import icon425 from '../../vendor/icon/svgs/tokens/tokenDenseVector.svg?unsafe-inline';
import icon426 from '../../vendor/icon/svgs/tokens/tokenElement.svg?unsafe-inline';
import icon427 from '../../vendor/icon/svgs/tokens/tokenEnum.svg?unsafe-inline';
import icon428 from '../../vendor/icon/svgs/tokens/tokenEnumMember.svg?unsafe-inline';
import icon429 from '../../vendor/icon/svgs/tokens/tokenEvent.svg?unsafe-inline';
import icon430 from '../../vendor/icon/svgs/tokens/tokenException.svg?unsafe-inline';
import icon431 from '../../vendor/icon/svgs/tokens/tokenField.svg?unsafe-inline';
import icon432 from '../../vendor/icon/svgs/tokens/tokenFile.svg?unsafe-inline';
import icon433 from '../../vendor/icon/svgs/tokens/tokenFlattened.svg?unsafe-inline';
import icon434 from '../../vendor/icon/svgs/tokens/tokenFunction.svg?unsafe-inline';
import icon435 from '../../vendor/icon/svgs/tokens/tokenGeo.svg?unsafe-inline';
import icon436 from '../../vendor/icon/svgs/tokens/tokenHistogram.svg?unsafe-inline';
import icon437 from '../../vendor/icon/svgs/tokens/tokenInterface.svg?unsafe-inline';
import icon438 from '../../vendor/icon/svgs/tokens/tokenIP.svg?unsafe-inline';
import icon439 from '../../vendor/icon/svgs/tokens/tokenJoin.svg?unsafe-inline';
import icon440 from '../../vendor/icon/svgs/tokens/tokenKey.svg?unsafe-inline';
import icon441 from '../../vendor/icon/svgs/tokens/tokenKeyword.svg?unsafe-inline';
import icon442 from '../../vendor/icon/svgs/tokens/tokenMethod.svg?unsafe-inline';
import icon443 from '../../vendor/icon/svgs/tokens/tokenMetricCounter.svg?unsafe-inline';
import icon444 from '../../vendor/icon/svgs/tokens/tokenMetricGauge.svg?unsafe-inline';
import icon445 from '../../vendor/icon/svgs/tokens/tokenModule.svg?unsafe-inline';
import icon446 from '../../vendor/icon/svgs/tokens/tokenNamespace.svg?unsafe-inline';
import icon447 from '../../vendor/icon/svgs/tokens/tokenNested.svg?unsafe-inline';
import icon448 from '../../vendor/icon/svgs/tokens/tokenNull.svg?unsafe-inline';
import icon449 from '../../vendor/icon/svgs/tokens/tokenNumber.svg?unsafe-inline';
import icon450 from '../../vendor/icon/svgs/tokens/tokenObject.svg?unsafe-inline';
import icon451 from '../../vendor/icon/svgs/tokens/tokenOperator.svg?unsafe-inline';
import icon452 from '../../vendor/icon/svgs/tokens/tokenPackage.svg?unsafe-inline';
import icon453 from '../../vendor/icon/svgs/tokens/tokenParameter.svg?unsafe-inline';
import icon454 from '../../vendor/icon/svgs/tokens/tokenPercolator.svg?unsafe-inline';
import icon455 from '../../vendor/icon/svgs/tokens/tokenProperty.svg?unsafe-inline';
import icon456 from '../../vendor/icon/svgs/tokens/tokenRange.svg?unsafe-inline';
import icon457 from '../../vendor/icon/svgs/tokens/tokenRankFeature.svg?unsafe-inline';
import icon458 from '../../vendor/icon/svgs/tokens/tokenRankFeatures.svg?unsafe-inline';
import icon459 from '../../vendor/icon/svgs/tokens/tokenRepo.svg?unsafe-inline';
import icon460 from '../../vendor/icon/svgs/tokens/tokenSearchType.svg?unsafe-inline';
import icon461 from '../../vendor/icon/svgs/tokens/tokenShape.svg?unsafe-inline';
import icon462 from '../../vendor/icon/svgs/tokens/tokenString.svg?unsafe-inline';
import icon463 from '../../vendor/icon/svgs/tokens/tokenStruct.svg?unsafe-inline';
import icon464 from '../../vendor/icon/svgs/tokens/tokenSymbol.svg?unsafe-inline';
import icon465 from '../../vendor/icon/svgs/tokens/tokenTag.svg?unsafe-inline';
import icon466 from '../../vendor/icon/svgs/tokens/tokenText.svg?unsafe-inline';
import icon467 from '../../vendor/icon/svgs/tokens/tokenTokenCount.svg?unsafe-inline';
import icon468 from '../../vendor/icon/svgs/tokens/tokenVariable.svg?unsafe-inline';

import type { typeToPathMap } from '../utils/css-mappings/eui-icon.ts';
import type { ComponentLike } from '@glint/template';

export type EuiIconComponent = ComponentLike<{
  Element: SVGSVGElement;
  Blocks: { default: [] };
}>;

const icons: Record<keyof typeof typeToPathMap, EuiIconComponent> = {
  "accessibility": icon0,
  "addDataApp": icon1,
  "advancedSettingsApp": icon2,
  "agentApp": icon3,
  "aggregate": icon4,
  "analyzeEvent": icon5,
  "annotation": icon6,
  "apmApp": icon7,
  "apmTrace": icon8,
  "appSearchApp": icon9,
  "apps": icon10,
  "arrowDown": icon11,
  "arrowLeft": icon12,
  "arrowRight": icon13,
  "arrowUp": icon14,
  "arrowStart": icon15,
  "arrowEnd": icon16,
  "article": icon17,
  "asterisk": icon18,
  "auditbeatApp": icon19,
  "beaker": icon20,
  "bell": icon21,
  "bellSlash": icon22,
  "beta": icon23,
  "bolt": icon24,
  "boxesHorizontal": icon25,
  "boxesVertical": icon26,
  "branch": icon27,
  "branchUser": icon28,
  "broom": icon29,
  "brush": icon30,
  "bug": icon31,
  "bullseye": icon32,
  "calendar": icon33,
  "canvasApp": icon34,
  "casesApp": icon35,
  "check": icon36,
  "checkInCircleFilled": icon37,
  "cheer": icon38,
  "classificationJob": icon39,
  "clock": icon40,
  "cloudDrizzle": icon41,
  "cloudStormy": icon42,
  "cloudSunny": icon43,
  "cluster": icon44,
  "codeApp": icon45,
  "color": icon46,
  "compute": icon47,
  "console": icon48,
  "consoleApp": icon49,
  "container": icon50,
  "continuityAbove": icon51,
  "continuityAboveBelow": icon52,
  "continuityBelow": icon53,
  "continuityWithin": icon54,
  "controlsHorizontal": icon55,
  "controlsVertical": icon56,
  "copy": icon57,
  "copyClipboard": icon58,
  "createAdvancedJob": icon59,
  "createMultiMetricJob": icon60,
  "createPopulationJob": icon61,
  "createSingleMetricJob": icon62,
  "cross": icon63,
  "crossClusterReplicationApp": icon64,
  "crosshairs": icon65,
  "currency": icon66,
  "cut": icon67,
  "dashboardApp": icon68,
  "dataVisualizer": icon69,
  "database": icon70,
  "desktop": icon71,
  "devToolsApp": icon72,
  "discoverApp": icon73,
  "discuss": icon74,
  "document": icon75,
  "documentEdit": icon76,
  "documentation": icon77,
  "documents": icon78,
  "dot": icon79,
  "dotInCircle": icon80,
  "doubleArrowLeft": icon81,
  "doubleArrowRight": icon82,
  "download": icon83,
  "editorAlignCenter": icon84,
  "editorAlignLeft": icon85,
  "editorAlignRight": icon86,
  "editorBold": icon87,
  "editorChecklist": icon88,
  "editorCodeBlock": icon89,
  "editorComment": icon90,
  "editorDistributeHorizontal": icon91,
  "editorDistributeVertical": icon92,
  "editorHeading": icon93,
  "editorItalic": icon94,
  "editorItemAlignBottom": icon95,
  "editorItemAlignCenter": icon96,
  "editorItemAlignLeft": icon97,
  "editorItemAlignMiddle": icon98,
  "editorItemAlignRight": icon99,
  "editorItemAlignTop": icon100,
  "editorLink": icon101,
  "editorOrderedList": icon102,
  "editorPositionBottomLeft": icon103,
  "editorPositionBottomRight": icon104,
  "editorPositionTopLeft": icon105,
  "editorPositionTopRight": icon106,
  "editorRedo": icon107,
  "editorStrike": icon108,
  "editorTable": icon109,
  "editorUnderline": icon110,
  "editorUndo": icon111,
  "editorUnorderedList": icon112,
  "email": icon113,
  "empty": icon114,
  "emsApp": icon115,
  "eql": icon116,
  "eraser": icon117,
  "error": icon118,
  "exit": icon119,
  "expand": icon120,
  "expandMini": icon121,
  "exportAction": icon122,
  "eye": icon123,
  "eyeClosed": icon124,
  "faceHappy": icon125,
  "faceNeutral": icon126,
  "faceSad": icon127,
  "filebeatApp": icon128,
  "filter": icon129,
  "filterExclude": icon130,
  "filterIgnore": icon131,
  "filterInclude": icon132,
  "filterInCircle": icon133,
  "flag": icon134,
  "fleetApp": icon135,
  "fold": icon136,
  "folderCheck": icon137,
  "folderClosed": icon138,
  "folderExclamation": icon139,
  "folderOpen": icon140,
  "frameNext": icon141,
  "framePrevious": icon142,
  "fullScreen": icon143,
  "fullScreenExit": icon144,
  "function": icon145,
  "gear": icon146,
  "gisApp": icon147,
  "glasses": icon148,
  "globe": icon149,
  "grab": icon150,
  "grabHorizontal": icon151,
  "graphApp": icon152,
  "grid": icon153,
  "grokApp": icon154,
  "heart": icon155,
  "heartbeatApp": icon156,
  "heatmap": icon157,
  "help": icon158,
  "home": icon159,
  "iInCircle": icon160,
  "image": icon161,
  "importAction": icon162,
  "indexClose": icon163,
  "indexEdit": icon164,
  "indexFlush": icon165,
  "indexManagementApp": icon166,
  "indexMapping": icon167,
  "indexOpen": icon168,
  "indexPatternApp": icon169,
  "indexRollupApp": icon170,
  "indexRuntime": icon171,
  "indexSettings": icon172,
  "indexTemporary": icon173,
  "infinity": icon174,
  "inputOutput": icon175,
  "inspect": icon176,
  "invert": icon177,
  "ip": icon178,
  "keyboard": icon179,
  "kqlField": icon180,
  "kqlFunction": icon181,
  "kqlOperand": icon182,
  "kqlSelector": icon183,
  "kqlValue": icon184,
  "kubernetesNode": icon185,
  "kubernetesPod": icon186,
  "launch": icon187,
  "layers": icon188,
  "lensApp": icon189,
  "lettering": icon190,
  "lineDashed": icon191,
  "lineDotted": icon192,
  "lineSolid": icon193,
  "link": icon194,
  "list": icon195,
  "listAdd": icon196,
  "lock": icon197,
  "lockOpen": icon198,
  "logoAWS": icon199,
  "logoAWSMono": icon200,
  "logoAerospike": icon201,
  "logoApache": icon202,
  "logoAppSearch": icon203,
  "logoAzure": icon204,
  "logoAzureMono": icon205,
  "logoBeats": icon206,
  "logoBusinessAnalytics": icon207,
  "logoCeph": icon208,
  "logoCloud": icon209,
  "logoCloudEnterprise": icon210,
  "logoCode": icon211,
  "logoCodesandbox": icon212,
  "logoCouchbase": icon213,
  "logoDocker": icon214,
  "logoDropwizard": icon215,
  "logoElastic": icon216,
  "logoElasticStack": icon217,
  "logoElasticsearch": icon218,
  "logoEnterpriseSearch": icon219,
  "logoEtcd": icon220,
  "logoGCP": icon221,
  "logoGCPMono": icon222,
  "logoGithub": icon223,
  "logoGmail": icon224,
  "logoGolang": icon225,
  "logoGoogleG": icon226,
  "logoHAproxy": icon227,
  "logoIBM": icon228,
  "logoIBMMono": icon229,
  "logoKafka": icon230,
  "logoKibana": icon231,
  "logoKubernetes": icon232,
  "logoLogging": icon233,
  "logoLogstash": icon234,
  "logoMaps": icon235,
  "logoMemcached": icon236,
  "logoMetrics": icon237,
  "logoMongodb": icon238,
  "logoMySQL": icon239,
  "logoNginx": icon240,
  "logoObservability": icon241,
  "logoOsquery": icon242,
  "logoPhp": icon243,
  "logoPostgres": icon244,
  "logoPrometheus": icon245,
  "logoRabbitmq": icon246,
  "logoRedis": icon247,
  "logoSecurity": icon248,
  "logoSiteSearch": icon249,
  "logoSketch": icon250,
  "logoSlack": icon251,
  "logoUptime": icon252,
  "logoVulnerabilityManagement": icon253,
  "logoWebhook": icon254,
  "logoWindows": icon255,
  "logoWorkplaceSearch": icon256,
  "logsApp": icon257,
  "logstashFilter": icon258,
  "logstashIf": icon259,
  "logstashInput": icon260,
  "logstashOutput": icon261,
  "logstashQueue": icon262,
  "machineLearningApp": icon263,
  "magnet": icon264,
  "magnifyWithExclamation": icon265,
  "magnifyWithMinus": icon266,
  "magnifyWithPlus": icon267,
  "managementApp": icon268,
  "mapMarker": icon269,
  "memory": icon270,
  "menu": icon271,
  "menuDown": icon272,
  "menuLeft": icon273,
  "menuRight": icon274,
  "menuUp": icon275,
  "merge": icon276,
  "metricbeatApp": icon277,
  "metricsApp": icon278,
  "minimize": icon279,
  "minus": icon280,
  "minusInCircle": icon281,
  "minusInCircleFilled": icon282,
  "mobile": icon283,
  "monitoringApp": icon284,
  "moon": icon285,
  "namespace": icon286,
  "nested": icon287,
  "node": icon288,
  "notebookApp": icon289,
  "number": icon290,
  "offline": icon291,
  "online": icon292,
  "outlierDetectionJob": icon293,
  "package": icon294,
  "packetbeatApp": icon295,
  "pageSelect": icon296,
  "pagesSelect": icon297,
  "paperClip": icon298,
  "partial": icon299,
  "pause": icon300,
  "payment": icon301,
  "pencil": icon302,
  "percent": icon303,
  "pin": icon304,
  "pinFilled": icon305,
  "pipelineApp": icon306,
  "pivot": icon307,
  "play": icon308,
  "playFilled": icon309,
  "plus": icon310,
  "plusInCircle": icon311,
  "plusInCircleFilled": icon312,
  "popout": icon313,
  "push": icon314,
  "questionInCircle": icon315,
  "quote": icon316,
  "recentlyViewedApp": icon317,
  "refresh": icon318,
  "regressionJob": icon319,
  "reporter": icon320,
  "reportingApp": icon321,
  "returnKey": icon322,
  "save": icon323,
  "savedObjectsApp": icon324,
  "scale": icon325,
  "search": icon326,
  "searchProfilerApp": icon327,
  "securityAnalyticsApp": icon328,
  "securityApp": icon329,
  "securitySignal": icon330,
  "securitySignalDetected": icon331,
  "securitySignalResolved": icon332,
  "sessionViewer": icon333,
  "shard": icon334,
  "share": icon335,
  "snowflake": icon336,
  "sortAscending": icon337,
  "sortDescending": icon338,
  "sortDown": icon339,
  "sortLeft": icon340,
  "sortRight": icon341,
  "sortUp": icon342,
  "sortable": icon343,
  "spaces": icon344,
  "spacesApp": icon345,
  "sqlApp": icon346,
  "starEmpty": icon347,
  "starEmptySpace": icon348,
  "starFilled": icon349,
  "starFilledSpace": icon350,
  "starMinusEmpty": icon351,
  "starMinusFilled": icon352,
  "starPlusEmpty": icon353,
  "starPlusFilled": icon354,
  "stats": icon355,
  "stop": icon356,
  "stopFilled": icon357,
  "stopSlash": icon358,
  "storage": icon359,
  "string": icon360,
  "submodule": icon361,
  "sun": icon362,
  "swatchInput": icon363,
  "symlink": icon364,
  "tableDensityCompact": icon365,
  "tableDensityExpanded": icon366,
  "tableDensityNormal": icon367,
  "tableOfContents": icon368,
  "tag": icon369,
  "tear": icon370,
  "temperature": icon371,
  "timeline": icon372,
  "timelineWithArrow": icon373,
  "timelionApp": icon374,
  "timeRefresh": icon375,
  "timeslider": icon376,
  "training": icon377,
  "trash": icon378,
  "unfold": icon379,
  "unlink": icon380,
  "upgradeAssistantApp": icon381,
  "uptimeApp": icon382,
  "user": icon383,
  "userAvatar": icon384,
  "users": icon385,
  "usersRolesApp": icon386,
  "vector": icon387,
  "videoPlayer": icon388,
  "visArea": icon389,
  "visAreaStacked": icon390,
  "visBarHorizontal": icon391,
  "visBarHorizontalStacked": icon392,
  "visBarVertical": icon393,
  "visBarVerticalStacked": icon394,
  "visGauge": icon395,
  "visGoal": icon396,
  "visLine": icon397,
  "visMapCoordinate": icon398,
  "visMapRegion": icon399,
  "visMetric": icon400,
  "visPie": icon401,
  "visTable": icon402,
  "visTagCloud": icon403,
  "visText": icon404,
  "visTimelion": icon405,
  "visVega": icon406,
  "visVisualBuilder": icon407,
  "visualizeApp": icon408,
  "vulnerabilityManagementApp": icon409,
  "warning": icon410,
  "alert": icon410,
  "watchesApp": icon411,
  "wordWrap": icon412,
  "wordWrapDisabled": icon413,
  "workplaceSearchApp": icon414,
  "wrench": icon415,
  "tokenAlias": icon416,
  "tokenAnnotation": icon417,
  "tokenArray": icon418,
  "tokenBinary": icon419,
  "tokenBoolean": icon420,
  "tokenClass": icon421,
  "tokenCompletionSuggester": icon422,
  "tokenConstant": icon423,
  "tokenDate": icon424,
  "tokenDenseVector": icon425,
  "tokenElement": icon426,
  "tokenEnum": icon427,
  "tokenEnumMember": icon428,
  "tokenEvent": icon429,
  "tokenException": icon430,
  "tokenField": icon431,
  "tokenFile": icon432,
  "tokenFlattened": icon433,
  "tokenFunction": icon434,
  "tokenGeo": icon435,
  "tokenHistogram": icon436,
  "tokenInterface": icon437,
  "tokenIP": icon438,
  "tokenJoin": icon439,
  "tokenKey": icon440,
  "tokenKeyword": icon441,
  "tokenMethod": icon442,
  "tokenMetricCounter": icon443,
  "tokenMetricGauge": icon444,
  "tokenModule": icon445,
  "tokenNamespace": icon446,
  "tokenNested": icon447,
  "tokenNull": icon448,
  "tokenNumber": icon449,
  "tokenObject": icon450,
  "tokenOperator": icon451,
  "tokenPackage": icon452,
  "tokenParameter": icon453,
  "tokenPercolator": icon454,
  "tokenProperty": icon455,
  "tokenRange": icon456,
  "tokenRankFeature": icon457,
  "tokenRankFeatures": icon458,
  "tokenRepo": icon459,
  "tokenSearchType": icon460,
  "tokenShape": icon461,
  "tokenString": icon462,
  "tokenStruct": icon463,
  "tokenSymbol": icon464,
  "tokenTag": icon465,
  "tokenText": icon466,
  "tokenTokenCount": icon467,
  "tokenVariable": icon468
};

export default icons;

/** `data-type` attributes from the source svgs, used by EUI's CSS. */
export const iconDataTypes: Partial<
  Record<keyof typeof typeToPathMap, string>
> = {
  "logoElastic": "logoElastic"
};
